### ISSUE TITLE
Theft of 3d models

### ISSUE THREAD

**Issue by DamienDesmont** [TartaricAcid/ysm#102]
#Is it possible to access ysm files?

because a user published a video where models of the yes steve model were shown, which are 3d .ysm models

look at the video
https://youtu.be/uTgQ2a90ne8?si=6LgNAR6eqnGfkthr

but, that user is not the owner, he just made a review of the Minecraft bedrock addon

What I understand is that an MCP user created this mod without copyright of the 3D models

addon page
https://monster-mcpe.com/mods/3171-waifus-3d-add-on-120119118.html

The official page was deleted and other users published the addon, this addon being filtered by some pages

Tell me, is it possible to access a .ysm file?

Also, could you report the addon page because it seems illegal to use 3D models without copyright****

**Comment by yuyanMC** [comment]
Probably not. According to what I know, the model of Silver Wolf in the video is shared in zip format but not ysm.

**Comment by yuyanMC** [comment]
I've just checked for other models, all shared in zip format.

**Comment by KLuoNuoYa** [comment]
Not possible, this addon can use these models because the models are distributed in zip format

**Comment by Desmond051** [comment]
> Acabo de buscar otros modelos, todos compartidos en formato zip.

Hi, I'm sorry to answer at this hour, but could you tell me where I can get the 3d .zip models?

**Comment by Desmond051** [comment]
Also, are the 3d models free?

**Comment by yuyanMC** [comment]
> > Acabo de buscar otros modelos, todos compartidos en formato zip.
> 
> Hi, I'm sorry to answer at this hour, but could you tell me where I can get the 3d .zip models?

https://pan.baidu.com/s/14jFmfhppLbNvZYbXccxR1w?pwd=e8dl
https://pan.quark.cn/s/ac33321d3568#/list/share
https://pan.quark.cn/s/9dec840acb84#/list/share
They are all free models.

**Comment by Desmond051** [comment]
> > > Acabo de buscar otros modelos, todos los compartidos en formato zip.
> > 
> > 
> > Hola, siento contestar a esta hora, pero ¿podrías decirme dónde puedo conseguir los modelos 3d .zip?
> 
> [https://pan.baidu.com/s/14jFmfhppLbNvZYbXccxR1w?pwd=e8dl ](https://pan.baidu.com/s/14jFmfhppLbNvZYbXccxR1w?pwd=e8dl) [https://pan.quark.cn/s/ac33321d3568#/list/share ](https://pan.quark.cn/s/ac33321d3568#/list/share) [https://pan.quark.cn/s/9dec840acb84#/ listar/compartir](https://pan.quark.cn/s/9dec840acb84#/list/share) Todos son modelos gratuitos.

Hello, can you send me the 3D model files?

**Comment by Desmond051** [comment]
It's just that it doesn't let me download the 3D models, the page

**Comment by Desmond051** [comment]
Hello?

**Comment by yuyanMC** [comment]
> > > > Acabo de buscar otros modelos, todos los compartidos en formato zip.
> > > 
> > > 
> > > Hola, siento contestar a esta hora, pero ¿podrías decirme dónde puedo conseguir los modelos 3d .zip?
> > 
> > 
> > [https://pan.baidu.com/s/14jFmfhppLbNvZYbXccxR1w?pwd=e8dl ](https://pan.baidu.com/s/14jFmfhppLbNvZYbXccxR1w?pwd=e8dl) [https://pan.quark.cn/s/ac33321d3568#/list/share ](https://pan.quark.cn/s/ac33321d3568#/list/share) [https://pan.quark.cn/s/9dec840acb84#/ listar/compartir](https://pan.quark.cn/s/9dec840acb84#/list/share) Todos son modelos gratuitos.
> 
> Hello, can you send me the 3D model files?

Sorry, but I don't know if I can redistribute these files, so I can't offer any help.

**Comment by Desmond051** [comment]
> > > > > Acabo de buscar otros modelos, todos los compartidos en formato zip.
> > > > 
> > > > 
> > > > Hola, siento contestar a esta hora, pero ¿podrías decirme dónde puedo conseguir los modelos 3d .zip?
> > > 
> > > 
> > > [https://pan.baidu.com/s/14jFmfhppLbNvZYbXccxR1w?pwd=e8dl ](https://pan.baidu.com/s/14jFmfhppLbNvZYbXccxR1w?pwd=e8dl) [https://pan.quark.cn/s/ac33321d3568#/list/share ](https://pan.quark.cn/s/ac33321d3568#/list/share) [https://pan.quark.cn/s/9dec840acb84#/ listar/compartir](https://pan.quark.cn/s/9dec840acb84#/list/share) Todos son modelos gratuitos.
> > 
> > 
> > Hola, ¿puedes enviarme los archivos del modelo 3D?
> 
> Lo siento, pero no sé si puedo redistribuir estos archivos, así que no puedo ofrecer ninguna ayuda.
Can you send me the file via WhatsApp, please?

**Comment by Desmond051** [comment]
Because if you send me the files discreetly, you will not be charged with anything.

**Comment by Desmond051** [comment]
Also, it is seen that in the video link the 3d models appear without giving copyright or paying

**Comment by Desmond051** [comment]
Can you send me the files via WhatsApp?
