### ISSUE TITLE
mod incompatibility with the first person mod

### ISSUE THREAD

**Issue by XSwiftxX** [TartaricAcid/ysm#103]
well , when playing the game using Yes steve model mod with the first person mod the player model overlaps the original model , the first person mod tries to show the player's full body but the YES steve model mod's player model covers the player's view , and make it unplayable , i want to play your mod with the ability to actually see me waving the weapon with my hand on the target , not just a weapon floating around 

please fix this ASAP !!
![image_2024-05-03_211252867](https://github.com/TartaricAcid/ysm/assets/168859544/101b83d8-604a-468b-b2a3-00416509371f)

**Comment by KLuoNuoYa** [comment]
What are the versions of the First Person Mod and Yes Steve Model?
