### ISSUE TITLE
java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by SakuraSayaka** [TartaricAcid/ysm#104]
This mod causes a java.lang.NullPointerException: null in my modpack when loading either single player worlds or servers
I have 153 mods in my modpack (originally 260+), and my previous attempts to exclude extraneous mods may have caused this issue to stop occurring every time I removed certain mods that didn't seem to be related in any way, such as AlwaysEat-5.2, amendments-1.20-1.1.22, another_ furniture-forge-1.20.1-3.0.1, appleskin-forge-mc1.20.1-2.5.1, astikorcarts-redux-1.20.1-1.1.7
I've tried removing all the mods that start with A in their names individually and the problem no longer occurs, but if I install them all at the same time the problem occurs. This happens not only with the mods listed above, but also with many others. Problems like this are too complex for me to go through almost countless reboots to shrink the number of mods.
Originally there was an occurrence of a group of mods all being deleted to fix the issue, and at the time I didn't realize it was the mod, until I deleted ysm and never ran into the issue again, no matter how many mods were installed after.
Here's my modlist, I can also upload a full modpack if needed!
[modlist.txt](https://github.com/TartaricAcid/ysm/files/15232751/modlist.txt)
[debug.log](https://github.com/TartaricAcid/ysm/files/15232453/debug.log)
[latest.log](https://github.com/TartaricAcid/ysm/files/15232454/latest.log)

**Comment by KLuoNuoYa** [comment]
Yes Steve Model didn't compatible with Better Combat

**Comment by SakuraSayaka** [comment]
> Yes Steve Model didn't compatible with Better Combat

I have deleted better combat before and it still happens.

**Comment by KLuoNuoYa** [comment]
Is there have no crash-report file?

**Comment by Aerolaxy** [comment]
Similar issue [https://github.com/TartaricAcid/ysm/issues/87](url)

**Comment by Aerolaxy** [comment]
#87 similar issue
