### ISSUE TITLE
[Iris(Oculus) Compatibility] java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by Akkar1n-Nyan** [TartaricAcid/ysm#105]
An error occurred with ysm when I tried to launch my client after I added the latest version (RC1) of Distant Horizons and the compatible mods.
**Mods Changes:**
> DistantHorizons-2.1.0-a-RC1-1.20.1.jar
embeddium-0.3.12+mc1.20.1.jar
embeddiumplus-1.20.1-v1.2.7.jar
oculus-flywheel-compat-1.20.1-0.2.5.jar
oculus-mc1.20.1-1.7.0.jar
textrues_embeddium_options-0.1.5+mc1.20.1.jar

It seems to be related with Iris (Oculus) compatibility.

![image](https://github.com/TartaricAcid/ysm/assets/152370047/f0807fc5-bf95-4f36-a5ae-8b9b3055ffd3)

[latest.log](https://github.com/TartaricAcid/ysm/files/15285717/latest.log)

**Comment by KLuoNuoYa** [comment]
Known issues, will be fixed in the next version.

**Comment by tangge233** [comment]
Has the problem been solved?

**Comment by KLuoNuoYa** [comment]
> Has the problem been solved?

will be fixed in next version
