### ISSUE TITLE
[1.19.2/Forge] FTB Skies整合包加入ysm后出现空指针错误

### ISSUE THREAD

**Issue by Sorrow-Scarlet** [TartaricAcid/ysm#107]
# 复现
- 使用FTB Skies整合包，加入最新hotfix4的ysm,创建新世界/进入现有存档。
- 无法创建/加入，提示Null Pointer。
- 移除ysm后正常。
- 期间一次log提示了自带的computercraft出现错误，可能不兼容ysm？
# LOG
-latest.log ：
[latest.log](https://github.com/TartaricAcid/ysm/files/15368775/latest.log)
-debug.log ：
[debug.log](https://github.com/TartaricAcid/ysm/files/15368777/debug.log)

**Comment by KLuoNuoYa** [comment]
Duplicated with #104

**Comment by TartaricAcid** [comment]
Fix in 2.2.1
