### ISSUE TITLE
模组服问题

### ISSUE THREAD

**Issue by tumuidle** [TartaricAcid/ysm#11]
装载后进模组服提示模组列表不匹配，看日志就只有ysm reject

[net.minecraftforge.fml.network.NetworkRegistry/NETREGISTRY]: Channels [yes_steve_model:network] rejected their server side version number

**Comment by TartaricAcid** [comment]
请提供更多详细信息，这看起来像是服务端客户端模组安装的不匹配导致的问题

**Comment by tumuidle** [comment]
就是模组服的服务端那边没有这个模组。。。
强制禁用forge这个检查会导致所有人变成默认模型且无法加载本地模型

**Comment by tumuidle** [comment]
有人吗。。。

**Comment by ayakasuki** [comment]
这个是需要服务端添加有这个模组才行吧 我们都是服主用

**Comment by tumuidle** [comment]
原版服就不冲突，进模组服会炸

**Comment by TartaricAcid** [comment]
本模组是一个客户端、服务端的双端模组，任何一端缺失都无法使用
