### ISSUE TITLE
Better combat compatibility / override (suggestion)

### ISSUE THREAD

**Issue by KrokusAstra** [TartaricAcid/ysm#113]
Hi, in February you said there is no Better Combat compatibility plans. Do you have any now? 
I have easier suggestion.
Maybe make something like "override" option in config file? Cuz now everytime i attack, camera is glitching into character model, and everything i see is inner YSM model textures. 
So if "Override == true", then YSM animations comes on top, and we have current situation. If ""Override == False", YMC displays it's own animations only incase there is no 3rd party animations going on, like Better Combat, different moveset mods etc. 
It's way easier than add full fledged compatibility, and allow users to install your mod just for ingame model, ignoring animations.
What do you think?
![image](https://github.com/TartaricAcid/ysm/assets/172990355/7e4cb586-7337-4856-91ae-f9e897ac7eee)

**Comment by KLuoNuoYa** [comment]
Why can't you remove one of the mods?

**Comment by KrokusAstra** [comment]
This is not the questiond dev should say to user.

Because one mod gives cool model, and the other - cool animations. Is it wrong to want both to make cool modpack? It's better to unite, than "i donwanna fix just cuz i donwanna without clear reason, just delete it".
It's not about just BC, it's about animations overall, like ParCool and other mods for movement. I'd better delete YSM than big chunk of the modpack.

**Comment by KLuoNuoYa** [comment]
> This is not the questiond dev should say to user.

I'm not the developer of this mod, thank you.

**Comment by minhduckd5** [comment]
Same issue, I'm glad you stated the problem
Someday a hero will show up and fix this

**Comment by KrokusAstra** [comment]
> Why can't you remove one of the mods?

Oh, sorry. Anyway dev place "won't work" on this issue, so nothing will change.
