### ISSUE TITLE
I use YSM v2.2.1 but it say java runtime version too low

### ISSUE THREAD

**Issue by shiranui09** [TartaricAcid/ysm#118]
Yes Steve Model has failed to load correctly that java.lang.runtime Exception: Java runtime version too low: 1.8.0_51

How solve it can fix or just update on java? what need required java version?

**Comment by KLuoNuoYa** [comment]
You can download latest java version here: https://www.azul.com/downloads/?version=java-8-lts&package=jdk#zulu
