### ISSUE TITLE
[Forge]YSM 2.2.1 在 CatServer1.18.2 退出时卡死

### ISSUE THREAD

**Issue by SakiDream** [TartaricAcid/ysm#120]
游戏版本: 1.18.2
YSM版本: 2.2.1

服务端: CatServer
java版本: JDK17

不装其它mod 不装plugin 只安装YSM的情况下 
使用stop等指令关闭服务端时 会卡在保存世界后的这个INFO后

没有logs输出 并占用大量CPU
必须强行关闭控制台才行

# 控制台截图
![UQ5OMMXGXBLL6C)B(60 T1Q](https://github.com/TartaricAcid/ysm/assets/69176540/1b09aa7d-ae57-4876-a165-2a9379b0714e)

# Logs
[logs.zip](https://github.com/user-attachments/files/15990528/logs.zip)

**Comment by TomatoPuddin** [comment]
这是 CatServer 破坏了 JVM 的 ShutdownHook 导致的问题，无法修复。原版 forge 服务端没这个问题

**Comment by SakiDream** [comment]
> 这是 CatServer 破坏了 JVM 的 ShutdownHook 导致的问题，无法修复。原版 forge 服务端没这个问题

好的 谢谢佬
