### ISSUE TITLE
Ysm.dll  Trojan Virus Issue 

### ISSUE THREAD

**Issue by Stabilizer360** [TartaricAcid/ysm#121]
After installing YSM mod 
it extracts some of the DLL Files and Windows thinks its a stupid virus  fix this issue so windows doesnot recognize its a Virus or unwanted app me and lot of people gonna get this issue

![image](https://github.com/TartaricAcid/ysm/assets/103765095/66f85497-ac0f-421f-a4b6-e8995bac7edb)

**Comment by TartaricAcid** [comment]
Version 2.2.2 uses digital signatures to solve this problem
