### ISSUE TITLE
MC 1.21 crash at launch caused by: org.apache.commons.lang3.NotImplementedException: Mac OS X is not supported. | M3 Mac | Prism Launcher 

### ISSUE THREAD

**Issue by dolooXu** [TartaricAcid/ysm#128]
Minecraft- 1.21
Fabric- 0.16.0
Launcher- Prism 8.4
Java- 21.0.3 aarch64, distributed by Microsoft. and Java- 21.0.1 aarch64 by Eclipse Adoptium 
Other mods- All disabled except YSM produce the same result

Upgrade from Java 17 to 21 because of Minecraft 1.21 requirement. But it appears Mac OSX is no longer supported and the game crash at launch with the following log.
https://mclo.gs/xrkawqi

I know MacOS is probably not supported by YSM devs. But YSM 1.1.5-hotfix2 was working well with Minecraft 1.20.1 and Java 17. It would be a shame if it's no longer available on Mac.

**Comment by KLuoNuoYa** [comment]
duplicated with #79

**Comment by dolooXu** [comment]
It seems Issue #79 resulted in the classic Mac vs PC feud rather than a fix or workaround. :(  Still, thank you for the info, been a good run while it lasts.

**Comment by TartaricAcid** [comment]
Currently, it is difficult to provide support for other platforms due to issues on each platform.
Sorry
