### ISSUE TITLE
可以出一个bukkit插件吗，让纯净服也能使用Yes Steve Model

### ISSUE THREAD

**Issue by Coloryr** [TartaricAcid/ysm#13]
分发模型、动作数据就行。
（或者给个插件信道我自己搓个插件也行

**Comment by TartaricAcid** [comment]
现在不是有龙核、萌芽这类的插件么？
所以这才是开发 forge 模组的原因

**Comment by MrHua269** [comment]
emmm，应该可以自己发包实现?()

**Comment by Coloryr** [comment]
> emmm，应该可以自己发包实现?()

闭源的，不知道数据包

**Comment by MrHua269** [comment]
> > emmm，应该可以自己发包实现?()
> 
> 闭源的，不知道数据包

我有个patch你康康吗（）

**Comment by MrHua269** [comment]
> > emmm，应该可以自己发包实现?()
> 
> 闭源的，不知道数据包
https://github.com/MikuMC/MikuServer/blob/master/patches/server/0003-Ysm-protocol-support-in-nms-with-simple-bukkit-api.patch

**Comment by Coloryr** [comment]
> > > emmm，应该可以自己发包实现?()
> > 
> > 
> > 闭源的，不知道数据包
> > https://github.com/MikuMC/MikuServer/blob/master/patches/server/0003-Ysm-protocol-support-in-nms-with-simple-bukkit-api.patch

这可以写插件了都

**Comment by Coloryr** [comment]
> > > emmm，应该可以自己发包实现?()
> > 
> > 
> > 闭源的，不知道数据包
> > https://github.com/MikuMC/MikuServer/blob/master/patches/server/0003-Ysm-protocol-support-in-nms-with-simple-bukkit-api.patch

不行，你这个绑死了

**Comment by MrHua269** [comment]
> > > > emmm，应该可以自己发包实现?()
> > > 
> > > 
> > > 闭源的，不知道数据包
> > > https://github.com/MikuMC/MikuServer/blob/master/patches/server/0003-Ysm-protocol-support-in-nms-with-simple-bukkit-api.patch
> 
> 不行，你这个绑死了

啊？（）

**Comment by MrHua269** [comment]
> 啊？（）
啊对（needauth啥的部分没写(）

**Comment by MrHua269** [comment]
> > > > emmm，应该可以自己发包实现?()
> > > 
> > > 
> > > 闭源的，不知道数据包
> > > https://github.com/MikuMC/MikuServer/blob/master/patches/server/0003-Ysm-protocol-support-in-nms-with-simple-bukkit-api.patch
> 
> 不行，你这个绑死了

emmm，可能这个模组的一些运行方式导致了让插件服务端去兼容这个模组的多个版本比较困难()，作者在把模型写入到缓存并发给玩家的时候，使用了objectoutputstream处理了一些东西导致模组里的一些东西一rename就会废掉()

**Comment by Coloryr** [comment]
> 

不是这个意思，是代码太依赖minecraft底层了，没法用插件信道实现

**Comment by MrHua269** [comment]
> > 
> 
> 不是这个意思，是代码太依赖minecraft底层了，没法用插件信道实现

应该可以()这个大部分就用了个发包的和nbt的()

**Comment by MrHua269** [comment]
> > > 
> > 
> > 不是这个意思，是代码太依赖minecraft底层了，没法用插件信道实现
> 
> 应该可以()这个大部分就用了个发包的和nbt的()

emmm，tracker部分应该有事件了()

**Comment by MrHua269** [comment]
> > 
> 
> 不是这个意思，是代码太依赖minecraft底层了，没法用插件信道实现

简单写了一个，你康康吗（）

**Comment by Coloryr** [comment]
> > > 
> > 
> > 不是这个意思，是代码太依赖minecraft底层了，没法用插件信道实现
> 
> 简单写了一个，你康康吗（）

看看你的

**Comment by MrHua269** [comment]
> > > > 
> > > 
> > > 
> > > 不是这个意思，是代码太依赖minecraft底层了，没法用插件信道实现
> > 
> > 
> > 简单写了一个，你康康吗（）
> 
> 看看你的
https://raw.githubusercontent.com/Era4FunMC/Files/main/myysm.7z

**Comment by MrHua269** [comment]
> > 
> 
> 不是这个意思，是代码太依赖minecraft底层了，没法用插件信道实现

emmm，我把多版本支持写好了然后删除了nms部分，源码在https://github.com/Era4FunMC/MyYsmNonFull

**Comment by Coloryr** [comment]
真不错

**Comment by TomatoPuddin** [comment]
bukkit 版已经在计划中了
