### ISSUE TITLE
游戏环境1.18.2 Forge 40.2.14 ysm版本2.2.1与鞘翅插槽Curious Elytra一起使用时导致崩溃

### ISSUE THREAD

**Issue by MuriyaTensei** [TartaricAcid/ysm#134]
如题，游戏可以正常加载进入，但把鞘翅放入饰品栏后会导致游戏崩溃，附崩溃报告文件
[crash-2024-07-29_20.50.50-client.txt](https://github.com/user-attachments/files/16413900/crash-2024-07-29_20.50.50-client.txt)

**Comment by TomatoPuddin** [comment]
把鞘翅插槽降回两年前的版本就能解决，下次更新会适配新版。

**Comment by TartaricAcid** [comment]
已修正
