### ISSUE TITLE
能否提供生成假人的API?

### ISSUE THREAD

**Issue by Pevernow** [TartaricAcid/ysm#135]
我想将YSM用于替换村民，或者制作NPC。

能否提供相应生成假人（NPC）并执行动作的API？

**Comment by TomatoPuddin** [comment]
下版本会支持 Curtain/Carpet 假人

**Comment by TartaricAcid** [comment]
2.2.2 版本已经完成对 Curtain/Carpet 假人的支持，此问题关闭
