### ISSUE TITLE
库文件缺失

### ISSUE THREAD

**Issue by DSLZL** [TartaricAcid/ysm#137]
https://paste.fastmirror.net/?bc06634c2225d125#AskwQJcfG4yD4dywcg8y6kKJcJV4hMgY43h5ERLNbRdS

**Comment by TomatoPuddin** [comment]
这是面板服的问题，不知道他们从哪儿拷了一份版本不对应的 libstdc++ 上来，得联系他们按照这个来 https://docs.qq.com/doc/DR0ZjQXRQSnBmanpZ

**Comment by DSLZL** [comment]
> 这是面板服的问题，不知道他们从哪儿拷了一份版本不对应的 libstdc++ 上来，得联系他们按照这个来 https://docs.qq.com/doc/DR0ZjQXRQSnBmanpZ

了解，多谢
