### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by claymorwan** [TartaricAcid/ysm#138]
Is there any Linux support planned ? I want to use this mod but I can't since ysm files aren't supported yet. Please I beg add Linux support

**Comment by MiskaDaeve** [comment]
See https://github.com/TartaricAcid/ysm/issues/79

**Comment by MiskaDaeve** [comment]
See https://web.archive.org/web/20240730025323/https://github.com/TartaricAcid/ysm/issues/79

**Comment by TartaricAcid** [comment]
Currently, it is difficult to provide support for other platforms due to issues on each platform.
Sorry

PS: I noticed that some people deliberately stoke a conflict, and have removed some comments

**Comment by junjunorganization** [comment]
https://web.archive.org/web/20240730025323/https://github.com/TartaricAcid/ysm/issues/79

**Comment by junjunorganization** [comment]
![373540590-d035cd68-819b-4a40-9f6c-6f8532d2dc1e](https://github.com/user-attachments/assets/b2a5db3c-5372-40fb-bd14-93df9c2dd53b)
