### ISSUE TITLE
服务器上模型超过2MB会溢出导致无法进入服务器

### ISSUE THREAD

**Issue by czqwq** [TartaricAcid/ysm#14]
版本1.19.2
在服务器里添加超过2MB的模型会导致溢出无法进入服务器
截图和latest文件链接: https://wwu.lanzoub.com/iVMcD0zc5t6d

**Comment by TartaricAcid** [comment]
https://www.curseforge.com/minecraft/mc-mods/packet-fixer
使用此模组可以解决问题，按理来说模型就不应该这么大
