### ISSUE TITLE
macOS下使用JDK22运行 报错org.apache.commons.lang3.NotImplementedException

### ISSUE THREAD

**Issue by Happymax** [TartaricAcid/ysm#140]
之前在1.18的服务器上用1.2.0版本是没问题的，macOS下也能正常启动，不过用的是JDK17。换上2.2.1之后，1.18和新的1.21都开不了。同时测试了macOS 15 ARM64和macOS 14 x86_64，结果一样。

错误报告：
[Server] java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'yes_steve_model'!
[Server] 	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403) ~[fabric-loader-0.16.0.jar:?]
[Server] 	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.16.0.jar:?]
[Server] 	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401) ~[fabric-loader-0.16.0.jar:?]
[Server] 	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.16.0.jar:?]
[Server] 	at net.minecraft.server.Main.main(Main.java:111) [server-intermediary.jar:?]
[Server] 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.0.jar:?]
[Server] 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.0.jar:?]
[Server] 	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.16.0.jar:?]
[Server] 	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.16.0.jar:?]
[Server] 	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric-server-launch.jar:1.0.1]
[Server] Caused by: org.apache.commons.lang3.NotImplementedException: Mac OS X is not supported
[Server] 	at com.elfmcys.yesstevemodel.oOoOOOOo0OO0oOoo0000O0.OoOOOoO0ooo0oO000O0o0O(Unknown Source) ~[yesstevemodel-fabric-1.21-2.2.1.jar:?]
[Server] 	at com.elfmcys.yesstevemodel.oOoOOOOo0OO0oOoo0000O0.OooOo0oOoOO0o00OO000oO00(Unknown Source) ~[yesstevemodel-fabric-1.21-2.2.1.jar:?]
[Server] 	at com.elfmcys.yesstevemodel.oOO0O00oO0O0O0o00o0O00Oo.OooOo0oOoOO0o00OO000oO00(Unknown Source) ~[yesstevemodel-fabric-1.21-2.2.1.jar:?]
[Server] 	at com.elfmcys.yesstevemodel.YesSteveModel.onInitialize(Unknown Source) ~[yesstevemodel-fabric-1.21-2.2.1.jar:?]
[Server] 	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.0.jar:?]
[Server] 	... 7 more

**Comment by MiskaDaeve** [comment]
See https://github.com/TartaricAcid/ysm/issues/79

**Comment by MiskaDaeve** [comment]
See https://web.archive.org/web/20240730025323/https://github.com/TartaricAcid/ysm/issues/79

**Comment by TartaricAcid** [comment]
Currently, it is difficult to provide support for other platforms due to issues on each platform.
Sorry

PS: I noticed that some people deliberately stoke a conflict, and have removed some comments

**Comment by junjunorganization** [comment]
https://web.archive.org/web/20240000000000*/https://github.com/TartaricAcid/ysm/issues/79
