### ISSUE TITLE
yes-steve-model 的 modrinth 和 curseforge 的mod发布页面404

### ISSUE THREAD

**Issue by hakuryv** [TartaricAcid/ysm#141]
![Screenshot 2024-08-14 190200](https://github.com/user-attachments/assets/6a4035ce-552c-4664-93da-afe7f47a3370)
![image](https://github.com/user-attachments/assets/fad9e5c3-d7e8-4054-814f-5f06ecc6b99d)

**Comment by TartaricAcid** [comment]
Modrith 的已经恢复，cf 的是我们主动删除的
