### ISSUE TITLE
YSM client is not supported on linux （Questions）

### ISSUE THREAD

**Issue by HenryZeng-Zero** [TartaricAcid/ysm#143]
+ Mod version: yesstevemodel-fabric-1.20-2.2.1.jar
+ MC version: 1.20.1
+ fabric version: 0.15.11
+ Java Version: openjdk 21.0.3+9
+ OS: NixOS 24.05

我查阅了已经 closed 的 issues, 发现已经存在两个相同的问题了，所以在这里我有几个疑问：
1. 未来是否在客户端计划支持 Linux ？
2. 目前支持 Linux 有什么困难？
3. 是否允许其他开发者帮助修复该问题？

期望得到解答，感谢。

**Comment by MiskaDaeve** [comment]
See https://github.com/TartaricAcid/ysm/issues/79

**Comment by HenryZeng-Zero** [comment]
好吧，既然如此，我要考虑对ysm逆向或者重新开发代替品这样的选项了。

**Comment by TomatoPuddin** [comment]
期待

**Comment by TTsdzb** [comment]
期待。虽然保护作者成果可以理解并且值得赞赏，但这样激进的做法未免太不自由了

**Comment by MiskaDaeve** [comment]
> 好吧，既然如此，我要考虑对ysm逆向或者重新开发代替品这样的选项了。

It's close to impossible because it seems they used an cracked and modified VMP and the dll libraries are virtualized.

**Comment by MiskaDaeve** [comment]
> 期待。虽然保护作者成果可以理解并且值得赞赏，但这样激进的做法未免太不自由了
Well, they also did many other such things

**Comment by MiskaDaeve** [comment]
> 好吧，既然如此，我要考虑对ysm逆向或者重新开发代替品这样的选项了。

And if you are interested, we can talk on Discord(You can found it on my profile page)

**Comment by MiskaDaeve** [comment]
> 期待。虽然保护作者成果可以理解并且值得赞赏，但这样激进的做法未免太不自由了

They are trying to protect the interests of model developers and consider nothing about the users and the thrid-party developers. As you see, they have gave up so many users such ARM, Linux, MacOS users.

**Comment by MiskaDaeve** [comment]
This is kinda unresponsible

**Comment by MiskaDaeve** [comment]
> This is kinda unresponsible

<del>In the extreme, they just think about how to make it easier for the model authors</del>

**Comment by TartaricAcid** [comment]
Linux 客户端的 API 经常变动，而且由于开发者的现实原因，我们缺乏时间和技术能力来完成相关 API 的兼容适配

我们注意到故意有部分人恶意评论激化矛盾，已经移除了部分拱火浇油的评论，多有打搅

**Comment by junjunorganization** [comment]
https://web.archive.org/web/20240000000000*/https://github.com/TartaricAcid/ysm/issues/79

**Comment by junjunorganization** [comment]
> Linux 客户端的 API 经常变动，而且由于开发者的现实原因，我们缺乏时间和技术能力来完成相关 API 的兼容适配
> 
> 我们注意到故意有部分人恶意评论激化矛盾，请不要被这些言论所误导。我已经移除了部分拱火浇油的评论，多有打搅

![图片](https://github.com/user-attachments/assets/ba6eb99a-2318-4730-92c1-5ca21cae9abd)
What are y trying to covering

**Comment by junjunorganization** [comment]
> > Linux 客户端的 API 经常变动，而且由于开发者的现实原因，我们缺乏时间和技术能力来完成相关 API 的兼容适配
> > 我们注意到故意有部分人恶意评论激化矛盾，请不要被这些言论所误导。我已经移除了部分拱火浇油的评论，多有打搅
> 
> ![图片](https://private-user-images.githubusercontent.com/82265683/373998082-ba6eb99a-2318-4730-92c1-5ca21cae9abd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyNjU2NTMsIm5iZiI6MTcyODI2NTM1MywicGF0aCI6Ii84MjI2NTY4My8zNzM5OTgwODItYmE2ZWI5OWEtMjMxOC00NzMwLTkyYzEtNWNhMjFjYWU5YWJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA3VDAxNDIzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzZWQwZjk5ZTA2M2E2ODY4ZTYzMzYwODFiOTdjYmUyYjRhMzY2M2RjODNhYWJhZmUzYjU5ZjU0OWM5NmZjZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.JiPAz5ODw0LDjHjjD_7M_A4VVjBZ4GD6yCZfUCcWnu4) WHAT ARE YOU TRYING TO COVERING
