### ISSUE TITLE
Please add Linux Support

### ISSUE THREAD

**Issue by VKilko** [TartaricAcid/ysm#145]
**I want to use this in forge and fabric on Linux.**

**Comment by XymaScope** [comment]
Seconded, you've probably heard the arguments but its important.

**Comment by MiskaDaeve** [comment]
See https://github.com/TartaricAcid/ysm/issues/79

**Comment by MiskaDaeve** [comment]
See https://web.archive.org/web/20240730025323/https://github.com/TartaricAcid/ysm/issues/79

**Comment by TartaricAcid** [comment]
Currently we support **Linux servers**，it is difficult to provide support for other platforms due to issues on each platform.
Sorry

PS: I noticed that some people deliberately stoke a conflict, and have removed some comments
