### ISSUE TITLE
aarch64 Support?

### ISSUE THREAD

**Issue by pasutafukurou** [TartaricAcid/ysm#147]
Hi, when I tried to run YSM with my OCI server it crashed. 
Will there be aarch64 support in the future or is there any workaround for this? 
Thanks for your time,
[2024-09-19-3.log](https://github.com/user-attachments/files/17084265/2024-09-19-3.log)

**Comment by MiskaDaeve** [comment]
Well, see https://github.com/TartaricAcid/ysm/issues/79

**Comment by MiskaDaeve** [comment]
> Well, see https://github.com/TartaricAcid/ysm/issues/79

Also including this issue

**Comment by MiskaDaeve** [comment]
See https://web.archive.org/web/20240730025323/https://github.com/TartaricAcid/ysm/issues/79

**Comment by TartaricAcid** [comment]
Currently, it is difficult to provide support for other platforms due to issues on each platform.
Sorry

PS: I noticed that some people deliberately stoke a conflict, and have removed some comments

**Comment by junjunorganization** [comment]
![373540590-d035cd68-819b-4a40-9f6c-6f8532d2dc1e](https://github.com/user-attachments/assets/c20eb83b-68f5-46fe-b217-74220ec731d4)

**Comment by junjunorganization** [comment]
https://web.archive.org/web/20240000000000*/https://github.com/TartaricAcid/ysm/issues/79
