### ISSUE TITLE
在FCL使用YSM发生报错

### ISSUE THREAD

**Issue by SSChen09** [TartaricAcid/ysm#149]
启动器FoldCraftLauncher 版本Fabric 1.21.1
日志：[fcl-latest6416839959835819533.zip](https://github.com/user-attachments/files/17231910/fcl-latest6416839959835819533.zip)

**Comment by MiskaDaeve** [comment]
See https://web.archive.org/web/20240730025323/https://github.com/TartaricAcid/ysm/issues/79

**Comment by somerui** [comment]
YSM不支持任何非Windows amd64环境。

**Comment by MiskaDaeve** [comment]
As that saying goes:
![图片](https://github.com/user-attachments/assets/16a00af3-4162-46e6-8639-1cafe492514f)

**Comment by TartaricAcid** [comment]
因为架构原因，目前无法支持手机游玩，此问题关闭
