### ISSUE TITLE
Attacking render issue

### ISSUE THREAD

**Issue by LegendaryCrystalFox** [TartaricAcid/ysm#15]
All models seem to have an issue when attacking that the model face glitches onto the screen when swinging a sword.
![2023-06-26_15 41 22](https://github.com/TartaricAcid/ysm/assets/34899528/2ff375bd-5841-4276-8a79-1a6e81a943fa)

**Comment by TartaricAcid** [comment]
Sorry, I'm only compatible with Frist Person Model Mod
