### ISSUE TITLE
RealCamera mod compatibility

### ISSUE THREAD

**Issue by Aurarobe** [TartaricAcid/ysm#16]
Hello, first-off let me say i love your mod and would love to use it with the RealCamera mod, it already have a code for you to import so is it possible for this mod to add the compatibility? Thanks in advance!
https://github.com/xTracr/RealCamera/wiki/Compatible-With-Real-Camera

**Comment by TartaricAcid** [comment]
Sorry, I'm only compatible with First Person Model Mod
