### ISSUE TITLE
关于一些安全或是其他问题?()

### ISSUE THREAD

**Issue by Lora4967** [TartaricAcid/ysm#20]
emmmm,作者大大有考虑过发包漏洞的问题吗（），在我使用这个模组的时候发现了一些可能的问题：
1.模组中并没有限制玩家的发包速度，如果我反复给服务端发送空的缓存命中的数据包（对应模组中的O0OooooOO0o00O00Oo0O0Oo0类），服务端会一直发送全部模型直到发过来的包全部处理完，这样不会导致带宽或者I/O资源耗尽吗（
2.玩家在更改模型时向服务端发包服务端并不会检查这个包里指向的模型是否验证过，而是会直接处理然后将玩家更改模型的包发送给玩家

**Comment by TartaricAcid** [comment]
已解决
