### ISSUE TITLE
在使用光影和额外玩家模型渲染的情况下的严重性能缺损

### ISSUE THREAD

**Issue by TinyblackQvQ** [TartaricAcid/ysm#21]
以下测试结果来自于1.20.1-release-1.1.5-hotfix-3版本。
添加mod：Rubidium_0.6.5, Oculus_1.6.4, Spark_1.10.42；Minecraft版本：1.20.1_release；
————————————
关于模组内置的额外玩家模型渲染，似乎是单独独立渲染的，渲染线程放在GUI渲染上；而玩家模型的渲染是放在LevelRender里的，加了光影的情况下则在ShadowRenderer里还会额外渲染一次玩家模型。

关键问题是，在未开启光影的状态下，仅使用第一人称时不会渲染LevelRender里的玩家模型，只会渲染GUIRender里的玩家模型；但开启光影后，使用第一人称，则会在LevelRender里额外渲染一遍玩家模型来借此渲染阴影；使用第三人称时，则将在ShadowRender里、LevelRenderer里、GUIRender里各渲染一次玩家模型。
这也就意味着，当玩家开启光影后，将渲染两次玩家模型，且在ShadowRenderer里的渲染还会额外计算阴影。
两次甚至三次的玩家模型渲染可以说是占用了大量的渲染能力。

特别是使用高模时，模型的复杂程度会以三倍左右的程度大幅影响帧率：
未开启光影，使用第一人称，关闭额外玩家渲染，禁用渲染玩家模型；avgfps：288
未开启光影，使用第一人称，关闭额外玩家渲染；avgfps：241
未开启光影，使用第一人称，仅GUI渲染的玩家模型对渲染进程的占用即可达到60%；avgfps：103
未开启光影，使用第三人称，则GUI渲染占用36%，实体渲染占用21%+15%；avgfps：64
开启光影后，使用第一人称，关闭额外玩家渲染，禁用渲染玩家模型；avgfps：175
开启光影后，使用第一人称，关闭额外玩家渲染，则阴影渲染占用55%+16%；avgfps：39
开启光影后，使用第一人称，则GUI渲染占用17%，阴影渲染占用47%+12%；avgfps：34
开启光影后，使用第三人称，则GUI渲染占用11%，实体渲染占用31%+6%，阴影渲染占用30%+5%，avgfps：22
（+号内是指的计算顶点（vertex）所消耗的占用，一般情况下占用很低，GUI渲染的顶点计算好像是放在GUIRender内了）
同时按照这个逻辑来看，在服务器内，玩家开启光影、额外玩家渲染，使用第一人称视角游玩时，一般就会将玩家本身的模型渲染2次，其他玩家的模型也会渲染两次，其他玩家的数量也将大幅影响性能。

所以关于这一点，是否可以进行一定的优化来缓解这种多次渲染的现象。例如将一次模型渲染的结果给其他需要的进程使用，又或者可以写一个生成低模的用于压缩模型的功能，以供光影渲染、GUI渲染使用（很多时候玩家并不会将注意力转移在额外的玩家模型上）。

**Comment by Theoretical-Enday** [comment]
雖然太復雜的我不懂，但開啟光影的情況下使用自定模型的確會大幅度降低FPS
![QQ截图20231028221746](https://github.com/TartaricAcid/ysm/assets/73912246/1f7bc940-6716-4fe5-a109-7f63346354b5)
![QQ截图20231028221803](https://github.com/TartaricAcid/ysm/assets/73912246/8f8729b9-7e20-471a-b8f2-1b96a7dd6a74)

**Comment by Slaggold** [comment]
我也发现了这个问题，我的ysm为1.20.1-release-1.1.5-hotfix-2版本。
添加mod：sodium-fabric-mc 1.20.1-0.5.3, iris-mc1.20.1-1.6.10, starlight-1.1.2+fabric.dbc156f
Minecraft版本：1.20.1-Fabric 0.14.24
使用光影 ComplementaryUnbound_r5.1.1
显卡4060 8g 笔记本140w CPU i5-13500HX 32G内存 其他设置均为最适合游戏的设置
在使用高精度模型时，开启格外玩家渲染和开启光影的实时阴影效果会导致严重的掉帧120fps->40fps
在使用高精度模型时，关闭格外玩家渲染和开启光影的实时阴影效果会导致严重的掉帧120fps->60fps
在使用一般精度模型时，开启格外玩家渲染和开启光影的实时阴影效果不会导致严重的掉帧120fps->110fps
然而，如果关闭光影的实时阴影效果，无论怎么折腾，就算把其他除了阴影以外的效果全部开启最高，都不会有严重的掉帧
并且在使用高精度模型时，开启格外玩家渲染和开启光影的实时阴影效果时，我发现显卡的功率只有40W
但是在关闭实时阴影后或者使用低精度模型，显卡的功率会提升至2倍多，这样便不卡顿了，我不清楚这是什么原因导致的。
所以我觉得十分有必要优化渲染方式，就如同楼主说的那样。
对了，这个问题的标题能不能改的具体一些，“关于性能问题“未免有些太过宽泛，比如可以改成”在使用光影的情况下使用高精度模型会导致严重掉帧“
![屏幕截图 2023-12-05 214752](https://github.com/TartaricAcid/ysm/assets/52627520/7ece3b2e-64d1-463e-a035-941100a35dcb)
![屏幕截图 2023-12-05 214835](https://github.com/TartaricAcid/ysm/assets/52627520/65b06019-b5fe-48f2-877b-ebdd181dbb8f)

**Comment by TartaricAcid** [comment]
现在新版本已经能解决部分性能问题

但是请注意，这些模型本身就使用了过多的面（相对于原版的十几个面的模型，本模组的很多模型可能会使用多大数千，乃至上万个面），在如此大的性能影响下再使用光影，电脑本身就算不过来了。

所以，不得不承认我们实在无能为力
