### ISSUE TITLE
[1.20.1/1.16.5]疑似存在内存泄漏问题

### ISSUE THREAD

**Issue by TinyblackQvQ** [TartaricAcid/ysm#23]
由于代码加密过，无法分析函数的作用，我只能提供一些基本的信息。
——————————
该问题出自于一个包装Map的类，泄漏于其中的$arg1的ref。
该Map类型为Map<String, unknown_struct_1>
`public class Packaged_map{`
`    private final Map<String, unknown_struct_1> instance;`
`    public Packaged_map(Map<String, unknown_struct_1> paramMap) {`
`        this.instance = paramMap;`
`    }`
`    public Packaged_map() {`
`        this((Map<String, unknown_struct_1>)new Object2ObjectOpenHashMap());`
`    }`
`    public unknown_struct_1 getValue(String paramString){`
`        return this.instance.get(paramString);`
`    }`
`    public Collection<unknown_struct_1> getValues(){`
`        return this.instance.values();`
`    }`
`    public Map<String, unknown_struct_1> getInstance(){`
`        return this.instance;`
`    }`
`    public void put(String paramString, unknown_struct_1 paramStruct){`
`        this.instance.put(paramString, paramStruct);`
`    }`
`}`
unknown_struct_1类中只存放着一些数据，分别为：
`public class unknown_struct_1 {`
`    public String unknown_string;`
`    public double unknown_number = -1.0D;`
`    public Unknown_interface un_interface = Unknown_interface.instance.unknown_enum_1.default;`
`    public List<Unknown_Capacity> unknown_cap1;`
`    public List<Unknown_Capacity_2<String>> unknown_cap2 = (List<Unknown_Capacity_2<String>>) new ObjectArrayList;`
`    public List<Unknown_Capacity_3> unknown_cap3 = (List<Unknown_Capacity_3>new ObjectArrayList)new ObjectArrayList;`
`    public List<Unknown_Capacity_2<String>> unknown_cap4 = (List<Unknown_Capacity_2<String>>) new ObjectArrayList;`
`}`

经过内存快照查询，在该Map类型中只存储了两个数据：
$arg1, $arg2。
$arg1的ref指向存在一个异常的CurrentHashMap：
`public class unknown_class3<T, U>{`
**`    private final Map<T,U> conHashMap = new ConcurrentHashMap<>();`**
`    public static <T,U> Function<T,U> addIfNonKeyExistPublic(Function<T,U> paramFunction) {`
`        return (new unknown_class<>()).unknown_func2(paramFunction);`
`    }`
`    private Function<T,U> addIfNonKeyExist(Function<T,U> paramFunction){`
`        return paramObject -> this.conHashMap.computeIfAbsent((T)paramObject, paramFunction);`
`    }`
`}`
该CurrentHashMap被另一个有关Double2DoubleFunction的类大量调用addIfNonKeyExistPublic。
`public class unknown_class{`
`    private static final Function<unknown_class2, Double2DoubleFunction> unknown_function = unknown_class3.addIfNonKeyExistPublic(unknown_class::un_func);`
`    private static Double2DoubleFunction un_func(unknown_class2 paramclass2){`
`    switch(null.un_func[paramclass2.get_un_enum().orinal()]){`
`        case 1:`
`            return un_func(un_func(paramclass2.get_un_double()));`
`        default:`
`            return un_func(unknown_class::un_func);`
`    }`
`    private static double un_func(double paramDouble){ return paramDouble; }`
`    private static Double2DoubleFunction un_func(double paramDouble){`
`        boolean bool = (paramDouble != null) ? paramDouble.intValue() : true;`
`        double[] arrayOfDouble = un_func(bool);`
`    ...`
`    }`
`}`
从功能上看，该unknown_class似乎是用来建立一个函数表格，其接受值为一个unknown_class2，返回值则是Double2DoubleFunction。其中unknown_class2主要存储了两个数值，第一个是枚举类unknown_enum，第二个是一个double类型的数字。
`public enum unknown_enum{`
`    DEFAULT, CUSTOM, LINEAR, STEP;`
`    public static unknown_type DEFAULT(String paramString) {`
`        switch (paramString.toLowerCase(Locale.ROOT))`
`            {`
`                default:`
`                    return DEFAULT;`
`                case "custom:"`
`                    return CUSTOM;`
`                case "linear":`
`                    return LINEAR`
`                case "step":`
`                    break;`
`            }`
`        return STEP;`
`}`

`public class unknown_class2{`
`    private final unknown_enum un_enum;` //un_enum = unknown_enum.LINEAR
`    private final Double un_number;` //un_number = null
`   ...`
`}`
但在拉取的内存快照中，存在大量的k值类为unknown_class，v值类为unknown_enum的键值对，
同时，val的值为空，key值存在两个ref，第一个name与unknown_class中的unknown_function的名称相同，但类型为unknown_enum，其值为LINEAR，另外一个ref则指向null。

在key-unknown_function->LINEAR->name->hash中可知其哈希码计算为-2049342683

从拉取的内存快照来看，该ConcurrentHashMap总共存在17740488个入点，Shallow Heap达到了134217744bytes，Retained Heap达到了1543291848bytes。游戏总占用达到了2.7g。
当然这也可能只是建造的缓存映射表之类的东西，占用比较大，所以是否是内存泄漏还仍然存疑。
（看加密的代码都要看吐了，弄了一整天，现在脑袋里全是O000ooO（；´д｀）ゞ）
![image](https://github.com/TartaricAcid/ysm/assets/69118919/f9cdd8db-c14e-4db1-a749-b1ceed31f222)
![image](https://github.com/TartaricAcid/ysm/assets/69118919/7cd1d597-89f2-4197-9e2f-4f7234d8e902)
![image](https://github.com/TartaricAcid/ysm/assets/69118919/95d7ab19-db28-40b8-aaa6-69ea6f8a1312)
![image](https://github.com/TartaricAcid/ysm/assets/69118919/5cd29f52-4e30-4723-98cf-ee0378236efe)

**Comment by eikyu625** [comment]
在1.16的ysm上遇到了同样的问题，但是1.18没有此问题。不知是版本问题还是模组冲突...

**Comment by TartaricAcid** [comment]
已解决
