### ISSUE TITLE
客户端上传模型到服务器

### ISSUE THREAD

**Issue by MannyCooper** [TartaricAcid/ysm#24]
您好，

非常感谢开发、维护这么好的一个模组，我正在使用 1.19.2 forge 版本。
请问是否支持客户端 OP 通过 Alt+Y 的那个页面打开的模型文件夹导入，并上传到服务端呢？还是必须手动把模型直接放在服务端的对应文件夹里？（因为我测试从客户端导入没有效果）

**Comment by TinyblackQvQ** [comment]
This mod doesn't support the feature of uploading models from cilent.
It is designed to prevent some problem about model authorization.
The OPs(OP level 2) only have the ability to give a certain player the permission to use one model on server.
To add model files to the server, it's needed to be added from the server folder.
Meanwhile, the cilent cannot use the models it can use in the server when in other servers, including local worlds. Every model List on server is independent. For cilents to use the models on servers, the downloads have been encrypted before cilent can use  it. It's all for the safe using of the models, and to protect the modeler's work.
