### ISSUE TITLE
fabric服务端 1.20 出现 handleDisconnection() called twice问题

### ISSUE THREAD

**Issue by chen125666** [TartaricAcid/ysm#25]
fabric 1.20 出现 handleDisconnection() called twice问题 玩家无法连接到服务器
服务端使用的mods
yesstevemodel-1.20-fabric-release-1.1.5-hotfix-2 
ForgeConfigAPIPort-v8.0.0-1.20.1-Fabric
fabric-api-0.85.0+1.20.1
FabricProxy-Lite-2.6.0
删除ysm后玩家可以连接

**Comment by TomatoPuddin** [comment]
这是 Velocity 与 Fabric 自定义命令参数的兼容性问题，见 https://github.com/PaperMC/Velocity/issues/913 。解决方法是安装 [CrossStitch](https://modrinth.com/mod/crossstitch)，不过该模组还未更新 1.20 版本。

**Comment by Linux1145141919810** [comment]
同样问题，有什么替代方案吗？

**Comment by TomatoPuddin** [comment]
上述模组的 1.19.3 版本可以兼容 1.20.1 服务端

**Comment by TartaricAcid** [comment]
关闭此 Issues
