### ISSUE TITLE
(已解决)添加quilt加载器支持

### ISSUE THREAD

**Issue by cookie981** [TartaricAcid/ysm#26]
quilt加载器是能兼容fabric模组的，但ysmFabric版不支持，这是错误报告
[crash-2023-08-14_08.50.48-client.txt](https://github.com/TartaricAcid/ysm/files/12330839/crash-2023-08-14_08.50.48-client.txt)

**Comment by KLONOA9X6** [comment]
???

**Comment by TomatoPuddin** [comment]
quilt 并不完全兼容 fabric 模组，而且至今都还在 beta 阶段，玩家数量也不多，所以不会专门对 quilt 做兼容。

**Comment by cookie981** [comment]
> ??? <img alt="790d66acd3ad2b1d9e78138bc5fb5303" width="971" src="https://user-images.githubusercontent.com/95112579/260663132-f7ad9e96-c98f-4268-8590-5019f5a29dad.png"> <img alt="eb1e51ca3da78a335af456b16e365355" width="971" src="https://user-images.githubusercontent.com/95112579/260663166-859c0dbb-2a47-49e1-bdf5-d1bce5903175.png"> <img alt="fd140f1e39056df33eee582baec0dcd5" width="971" src="https://user-images.githubusercontent.com/95112579/260663187-fa70961d-4757-459b-8d7f-82c6f2e6816e.png">

你安装最新版本的quilt加载器试一试，比如beta.14，我猜应该是quilt的问题

**Comment by cookie981** [comment]
找到稳定的复现步骤了，1.20.1版本，quilt只要是beta5以上的版本，安装quilt-api，ForgeConfigAPIPort，YSM的最新版本以外，再加上其他模组，很大概率会崩溃，比如modmenu。
所以至少现在不会对quilt进行兼容了？
