### ISSUE TITLE
fabric版趴下不生效

### ISSUE THREAD

**Issue by meishiffx** [TartaricAcid/ysm#27]
被活扳门趴下后模型依然站立

**Comment by TomatoPuddin** [comment]
如何复现趴不下的情况

![{C46EC1B6-15DE-4460-8676-9D889CAEDE1A}](https://github.com/TartaricAcid/ysm/assets/67496378/8c9feb3c-f68e-45f7-82aa-8b54c38f003a)

**Comment by meishiffx** [comment]
我的问题 是https://www.curseforge.com/minecraft/mc-mods/crawl这个模组导致的，应该是为了不在服务器被滥用改了什么
