### ISSUE TITLE
使用“Taterzens”NPC模组的NPC会有默认模型且无法修改

### ISSUE THREAD

**Issue by MSnjStudios** [TartaricAcid/ysm#28]
我安装了此模组之后，发现NPC不是之前的Alex模型，而是模组的默认模型，且无法修改。<b>NPC皮肤我是自定义了一个，有预设

**Comment by TomatoPuddin** [comment]
这 mod 用非标准的方式实现了 NPC 实体，导致其它 mod 要用针对性、侵入性的方法去兼容它，所以不打算做兼容。

**Comment by TartaricAcid** [comment]
新版已解决此问题，NPC 模组将会使用原版玩家渲染
