### ISSUE TITLE
[1.18.2]联机时玩家切换回默认史蒂夫模型后 客户端崩溃

### ISSUE THREAD

**Issue by OcrSu** [TartaricAcid/ysm#3]
[crash-2023-01-26_19.22.34-client.txt](https://github.com/TartaricAcid/ysm/files/10508857/crash-2023-01-26_19.22.34-client.txt)
[Uploading debug.log…]()
[Uploading latest.log…]()
[Uploading PCL2 启动器日志.txt…]()

**Comment by TartaricAcid** [comment]
局域网联机 bug，已在新版本中修复
