### ISSUE TITLE
模组的举盾动作不兼容其他模组的盾牌

### ISSUE THREAD

**Issue by mc-kaishixiaxue** [TartaricAcid/ysm#30]
模组版本：1.19.2-release-1.1.5-hotfix-2
模组的举盾动作只有使用原版盾牌才能生效，使用其他模组的盾牌时，如Mek附属“Mekanism Tools”的[盾牌](https://www.mcmod.cn/item/546330.html)，手臂一直摆动，播放使用动画。

**Comment by Apot98** [comment]
这个应该是因为用的模型只加了use_mainhand$minecraft:shield和use_offhand$minecraft:shield的持盾动画所以不兼容其他盾牌。不过确实可以考虑在ysm这个模组里加一些物品标签，然后让模型作者做动画的时候引用这个标签而非直接引用原版盾牌这个物品。

**Comment by KLONOA9X6** [comment]
请尝试使用minecraft:block动画

**Comment by TartaricAcid** [comment]
已解决，现在可以使用 use_mainhand:shield 名称动画来添加
