### ISSUE TITLE
在FABRIC客户端安装此模组，进入单机存档可以切换模型，进入纯净服务器(也就是没装这个mod的服务器)有时候可以切换模型有时候切换不了

### ISSUE THREAD

**Issue by zhjc2021** [TartaricAcid/ysm#31]
如题，十分玄学

**Comment by TomatoPuddin** [comment]
先进入单人游戏再进服务器就能切换模型。这本来是个漏洞，但是没什么危害，所以也没有修复的必要。
不过要注意进一些大型服务器可能会被判定为作弊，须自行承担后果。

**Comment by zhjc2021** [comment]
是这样的 我是一个正版公益服务器的服主 但是我们服务器是插件端（folia） 装不了mod
之前我偶然发现了这个漏洞，并且能在服务器里面切换模型 我特别高兴 我也只需要玩家自己能看见模型就行了
但是这个漏洞的触发很不稳定，我又试了好多次，都是进了服务器以后可以显示很多模型，但是点击没有反应，自己也只能用默认模型
不知道能否提供这个漏洞的稳定触发方式 或者是干脆添加一个功能 让玩家可以在游玩没有装这个mod的服务器时 也能在客户端自由的使用模型呢

**Comment by zhjc2021** [comment]
我想这个功能会很受欢迎，因为有不少正版公益服的玩家，他们都游玩在装不了这个mod的各种插件端服务器（如paper spigot bukkit folia），对于他们来说能在客户端看见自己的模型就很不错了

**Comment by MrHua269** [comment]
az,我有个fork支持这个mod的一些功能（）

**Comment by MrHua269** [comment]
这个mod的模型多人游戏的时候只有服务端发过来这个模型或者和客户端说有这个模型的时候好像才会加载或者让你切换（）

**Comment by zhjc2021** [comment]
我在昨天晚上，在没有装YSM的服务器里面成功看到了自己新加入的模型 甚至还截了图 可是再也无法复现了
https://s1.ax1x.com/2023/08/18/pP3kRPg.png
所以我想 这个功能（指在没有装YSM的服务器里面看自己的模型）是可能实现的

**Comment by MrHua269** [comment]
> 我在昨天晚上，在没有装YSM的服务器里面成功看到了自己新加入的模型 甚至还截了图 可是再也无法复现了
> https://s1.ax1x.com/2023/08/18/pP3kRPg.png
> 所以我想 这个功能（指在没有装YSM的服务器里面看自己的模型）是可能实现的

我写过()

**Comment by MrHua269** [comment]
> > 我在昨天晚上，在没有装YSM的服务器里面成功看到了自己新加入的模型 甚至还截了图 可是再也无法复现了
> > https://s1.ax1x.com/2023/08/18/pP3kRPg.png
> > 所以我想 这个功能（指在没有装YSM的服务器里面看自己的模型）是可能实现的
> 
> 我写过()

服务端不装这个其他装了ysm的玩家看不到你的模型()

**Comment by MrHua269** [comment]
> > > 我在昨天晚上，在没有装YSM的服务器里面成功看到了自己新加入的模型 甚至还截了图 可是再也无法复现了
> > > https://s1.ax1x.com/2023/08/18/pP3kRPg.png
> > > 所以我想 这个功能（指在没有装YSM的服务器里面看自己的模型）是可能实现的
> > 
> > 我写过()
> 
> 服务端不装这个其他装了ysm的玩家看不到你的模型()

不过应该是有个办法可以实现你issue里说的()

**Comment by zhjc2021** [comment]
其他人看不到我的模型无所谓 本来就是图一乐（

**Comment by zhjc2021** [comment]
> > 我在昨天晚上，在没有装YSM的服务器里面成功看到了自己新加入的模型 甚至还截了图 可是再也无法复现了
> > https://s1.ax1x.com/2023/08/18/pP3kRPg.png
> > 所以我想 这个功能（指在没有装YSM的服务器里面看自己的模型）是可能实现的
> 
> 我写过()

能分享下你写的附属mod或者魔改mod吗

**Comment by Anjiurine** [comment]
> 是这样的 我是一个正版公益服务器的服主 但是我们服务器是插件端（folia） 装不了mod 之前我偶然发现了这个漏洞，并且能在服务器里面切换模型 我特别高兴 我也只需要玩家自己能看见模型就行了 但是这个漏洞的触发很不稳定，我又试了好多次，都是进了服务器以后可以显示很多模型，但是点击没有反应，自己也只能用默认模型 不知道能否提供这个漏洞的稳定触发方式 或者是干脆添加一个功能 让玩家可以在游玩没有装这个mod的服务器时 也能在客户端自由的使用模型呢

实际上，在进入服务器之前先进入单人存档，然后保存并退出，再进入服务器就可以使用自己的模型了，这个触发方式很稳定

**Comment by Anjiurine** [comment]
不过还是希望官方能够支持仅客户端模式

**Comment by MrHua269** [comment]
> > 是这样的 我是一个正版公益服务器的服主 但是我们服务器是插件端（folia） 装不了mod 之前我偶然发现了这个漏洞，并且能在服务器里面切换模型 我特别高兴 我也只需要玩家自己能看见模型就行了 但是这个漏洞的触发很不稳定，我又试了好多次，都是进了服务器以后可以显示很多模型，但是点击没有反应，自己也只能用默认模型 不知道能否提供这个漏洞的稳定触发方式 或者是干脆添加一个功能 让玩家可以在游玩没有装这个mod的服务器时 也能在客户端自由的使用模型呢
> 
> 实际上，在进入服务器之前先进入单人存档，然后保存并退出，再进入服务器就可以使用自己的模型了，这个触发方式很稳定

emmm，ysm那个进入装了ysm的服务器之后服务器会向客户端发包通知客户端卸载掉自己已经加载的模型然后发送自己有的缓存到服务端，这也是为啥这个bug会有的原因，当然没有东西告知客户端这个客户端就会一直保留着这些模型()

**Comment by Anjiurine** [comment]
> > > 是这样的 我是一个正版公益服务器的服主 但是我们服务器是插件端（folia） 装不了mod 之前我偶然发现了这个漏洞，并且能在服务器里面切换模型 我特别高兴 我也只需要玩家自己能看见模型就行了 但是这个漏洞的触发很不稳定，我又试了好多次，都是进了服务器以后可以显示很多模型，但是点击没有反应，自己也只能用默认模型 不知道能否提供这个漏洞的稳定触发方式 或者是干脆添加一个功能 让玩家可以在游玩没有装这个mod的服务器时 也能在客户端自由的使用模型呢
> > 
> > 
> > 实际上，在进入服务器之前先进入单人存档，然后保存并退出，再进入服务器就可以使用自己的模型了，这个触发方式很稳定
> 
> emmm，ysm那个进入装了ysm的服务器之后服务器会向客户端发包通知客户端卸载掉自己已经加载的模型然后发送自己有的缓存到服务端，这也是为啥这个bug会有的原因，当然没有东西告知客户端这个客户端就会一直保留着这些模型()

a，理解了，虽然但是，官方迟迟不发布仅客户端模式，每次进入服务器都要反复触发bug，这让人很头疼（

**Comment by Anjiurine** [comment]
> > > 是这样的 我是一个正版公益服务器的服主 但是我们服务器是插件端（folia） 装不了mod 之前我偶然发现了这个漏洞，并且能在服务器里面切换模型 我特别高兴 我也只需要玩家自己能看见模型就行了 但是这个漏洞的触发很不稳定，我又试了好多次，都是进了服务器以后可以显示很多模型，但是点击没有反应，自己也只能用默认模型 不知道能否提供这个漏洞的稳定触发方式 或者是干脆添加一个功能 让玩家可以在游玩没有装这个mod的服务器时 也能在客户端自由的使用模型呢
> > 
> > 
> > 实际上，在进入服务器之前先进入单人存档，然后保存并退出，再进入服务器就可以使用自己的模型了，这个触发方式很稳定
> 
> emmm，ysm那个进入装了ysm的服务器之后服务器会向客户端发包通知客户端卸载掉自己已经加载的模型然后发送自己有的缓存到服务端，这也是为啥这个bug会有的原因，当然没有东西告知客户端这个客户端就会一直保留着这些模型()

能直接写一个拦截客户端数据包的mod吗，这样就可以伪装服务器返回来在本地使用了（

**Comment by Hoshino-Yumetsuki** [comment]
what can i say

**Comment by MiskaDaeve** [comment]
lol
