### ISSUE TITLE
与第一人称模组共同使用时，使autoVanillaHands无效化

### ISSUE THREAD

**Issue by An-thracene** [TartaricAcid/ysm#37]
我修改了firstperson的config使之与机械动力相兼容
![image](https://github.com/TartaricAcid/ysm/assets/96624949/83d904fb-c4a7-4ffd-a1c7-ca49198c56e9)
然而当使用ysm时其并没有生效
<img width="695" alt="image" src="https://github.com/TartaricAcid/ysm/assets/96624949/4599913d-4136-4a4f-8d49-30d999588d39">
版本：1.20.1 fabric 模组版本为最新

**Comment by TartaricAcid** [comment]
这种设计三个之间兼容性的问题无法解决，我们只能保持最低限度的兼容
