### ISSUE TITLE
半透明材质表现异常

### ISSUE THREAD

**Issue by QyInvoLing** [TartaricAcid/ysm#42]
游戏日志无异常。
角色模型如果包含使用了透明材质的部分，那么透明材质之后的内容将会出现渲染错误，比如错误地暴露模型内部内容、模型部分组件消失、区域变成完全透明以至于显示模型后面的东西等问题。
图见https://imgur.com/a/Ynarucp
模型发布在https://www.bilibili.com/video/BV1qj411t7RH，直接发文件可能会对原作者造成困扰，稍后我咨询一下原作者的意见

**Comment by TartaricAcid** [comment]
这是 OpenGL 本身的问题，无法解决

PS：原版实体也存在这个问题（比如透过信标看背后的水，材质就会丢失），甚至 Blockbench 本身就有这个问题（因为它用的是 WebGL，一套系统哈哈）

**Comment by TartaricAcid** [comment]
所以最好别用半透明材质
