### ISSUE TITLE
玩家渲染多次且模型位置不一

### ISSUE THREAD

**Issue by Ericmao232** [TartaricAcid/ysm#45]
https://github.com/TartaricAcid/ysm/assets/150097066/7a2b74bf-84e7-408c-8456-66c56860a0c9
1.18.2 forge mod版本1.1.5 hotfix 2  mod list： Oculus 1.6.4  Spark 1.9.11   Flywheel 0.6.8   iris-flywheel-compat-1.18.2-0.1.7-BETA
也会出现类似于https://github.com/TartaricAcid/ysm/issues/21 的bug 
且在第二 三人称下模型位置不一

**Comment by TartaricAcid** [comment]
已解决此问题
