### ISSUE TITLE
模组兼容

### ISSUE THREAD

**Issue by Dr-WeiAL** [TartaricAcid/ysm#5]
会跟[BetterCombat](https://www.curseforge.com/minecraft/mc-mods/better-combat-by-daedelus)这个模组兼容吗？
或者说这两个模组有兼容的可能吗？毕竟用的动画库都不一样
我也看到B站那个禁止渲染的视频了，只是问问(

现在同时安装这两个模组的时候第一人称攻击会看到自己的模型，在第三人称没有任何动作
![image](https://user-images.githubusercontent.com/47446553/227383397-54ed10b7-1e78-405b-83db-0a66f3d2fd47.png)
![image](https://user-images.githubusercontent.com/47446553/227383424-9c78706c-ee41-4825-a088-a995b258126a.png)

**Comment by TartaricAcid** [comment]
两个模组用了完全不同的代码和模型库，无法兼容

**Comment by Dr-WeiAL** [comment]
好的明白了
