### ISSUE TITLE
按 Y 会使游戏崩溃

### ISSUE THREAD

**Issue by SimonTheR** [TartaricAcid/ysm#50]
我注意到，当我按下 y 时，游戏会冻结并崩溃到启动器，并给我一个退出代码 -1。发生这种情况是因为 YSM 与其他模组冲突，还是织物的最新版本有问题（我使用的是 1.20 1.1.5 版 hotfix-2 版本，仅添加了 2 个模型），或者我只是“盲目”可以这么说

**Comment by TartaricAcid** [comment]
![image](https://github.com/TartaricAcid/ysm/assets/19620085/b9a8250e-be40-4b62-823f-60a8347fd60b)

**Comment by TartaricAcid** [comment]
你用的 Minecraft 版本是多少，是不是 1.20.2？
