### ISSUE TITLE
有可能兼容[EF] 史诗战斗 (Epic Fight)吗？

### ISSUE THREAD

**Issue by LSDGQ** [TartaricAcid/ysm#54]
想问一下该模组有可能兼容史诗战斗吗？因为挺喜欢你们的动作的 但是史诗战斗的兼容性我是知道的 如果不能兼容有没有可能去做一款像史诗战斗的模组  但是比史诗战斗好很多更多的兼容性

**Comment by TartaricAcid** [comment]
不可能
