### ISSUE TITLE
模组真的有必要混淆源码吗

### ISSUE THREAD

**Issue by 12345-mcpython** [TartaricAcid/ysm#55]
如题

**Comment by MIZUkiYuu** [comment]
第一次见有人用尊嘟假嘟混淆

**Comment by IBeiKui** [comment]
因为这个模组是闭源的嘛(

**Comment by 12345-mcpython** [comment]
我就见过这一个既闭源又混淆的模组
看崩溃日志起来麻烦不说扩展性又降低不少

**Comment by meishiffx** [comment]
闭源混淆都行，但是日志里面全是圈圈真的很难崩（

**Comment by TomatoPuddin** [comment]
不但有必要，而且下版本超级加倍

**Comment by KLONOA9X6** [comment]
> 我就见过这一个既闭源又混淆的模组 看崩溃日志起来麻烦不说扩展性又降低不少

非常有必要
一个很重要的原因是，模型防盗版

**Comment by Anjiurine** [comment]
> > 我就见过这一个既闭源又混淆的模组 看崩溃日志起来麻烦不说扩展性又降低不少
> 
> 非常有必要 一个很重要的原因是，模型防盗版

您是否需要：仅开源部分源码

**Comment by 12345-mcpython** [comment]
> > > 我就见过这一个既闭源又混淆的模组 看崩溃日志起来麻烦不说扩展性又降低不少
> > 
> > 
> > 非常有必要 一个很重要的原因是，模型防盗版
> 
> 您是否需要：仅开源部分源码

不如本体加密分离 jar 包

**Comment by KLONOA9X6** [comment]
> > > 我就见过这一个既闭源又混淆的模组 看崩溃日志起来麻烦不说扩展性又降低不少
> > 
> > 非常有必要 一个很重要的原因是，模型防盗版
> 
> 您是否需要：仅开源部分源码

他们下一步就是打算这么做的。

**Comment by Anjiurine** [comment]
> 主要是模型防盗用，所以实在无法暴露源码，抱歉了

加密部分可以不公开，其他部分公开也可以嘛

**Comment by MiskaDaeve** [comment]
> > > 我就见过这一个既闭源又混淆的模组 看崩溃日志起来麻烦不说扩展性又降低不少
> > 
> > 
> > 非常有必要 一个很重要的原因是，模型防盗版
> 
> 您是否需要：仅开源部分源码

他们无法把缓存和模型加载的分开，也就是说只要知道缓存或者ysm文件其中一种的解密方式，那么ysm文件的加密也就又形同虚设了,这个规律从ysm一开始到现在都仍然成立，所以开源版本大概率希望渺茫

**Comment by MiskaDaeve** [comment]
> > > > 我就见过这一个既闭源又混淆的模组 看崩溃日志起来麻烦不说扩展性又降低不少
> > > 
> > > 
> > > 非常有必要 一个很重要的原因是，模型防盗版
> > 
> > 
> > 您是否需要：仅开源部分源码
> 
> 他们无法把缓存和模型加载的分开，也就是说只要知道缓存或者ysm文件其中一种的解密方式，那么ysm文件的加密也就又形同虚设了,这个规律从ysm一开始到现在都仍然成立，所以开源版本大概率希望渺茫

而且目前来看，他们的JNI架构里的native部分可能有一些奇怪操作导致的可维护性较低
