### ISSUE TITLE
Server crashes on players entering world caused by invoking non-existent field

### ISSUE THREAD

**Issue by MUYUTwilighter** [TartaricAcid/ysm#58]
### Environment

> Both sides:
>> Java: Azule JDK 17.0.9 64bit
>> Minecraft: 1.20.1
>> Fabric: 0.15.6
>> Fabric API: 0.91.0
>> YSM: yesstevemodel-1.20-fabric-release-1.1.5-hotfix-2
>> Other mods installed:
>>> - geckolib-fabric-1.20.1-4.4.2
>>> - ForgeConfigAPIPort-v8.0.0-1.20.1-Fabric

### Records
Crash report(Server side): https://pastebin.com/k4cV7Hsc

Log(Server side): https://pastebin.com/AWauwNbZ

Log(Client Side): https://pastebin.com/Q3NkqrYg

### Decription

No matter geckolib is installed or not, when any player trying to connect to server, the server crashed immediately with traceback printed in crash report.

I tried to track the class that appears in trackback with Mixintrace, it seems that it was the field `PlayerMixin#OooOo0oOoOO0o00OO000oO00` is not correctly "mixed-in" to Player.class, which is indirectly invoked by class `OoOoOOO00OoOo00oooOoo00`.

**Comment by TartaricAcid** [comment]
Fix in 2.2.1
