### ISSUE TITLE
1.20.2版本ysm什么时候出？

### ISSUE THREAD

**Issue by FFFirewwwork** [TartaricAcid/ysm#59]
还是只发布1.20和1.20.1版本？1.20.2无法使用1.20以及1.20.2版本ysm

**Comment by FFFirewwwork** [comment]
1.20.2在使用1.20版本时加载没有问题，按y键打开ui会崩溃，进入服务器立即崩溃

**Comment by TomatoPuddin** [comment]
等1.21

**Comment by TartaricAcid** [comment]
1.20.2 是冷门版本，Minecraft 本体在这个小版本有较大变动，不会更新此版本
