### ISSUE TITLE
速度药水效果不会让walk和run动画加速播放

### ISSUE THREAD

**Issue by JackyBlackson** [TartaricAcid/ysm#6]
### 速度效果加快了玩家走路和疾跑的速度，但mod不会在效果下按照对应的提速比例增加walk和run动画的播放速度。
*  MC原版中会把视角晃动按照对应比例增加速度
* 生物受惊之后，移动速度加快时，原版播放的动画也会相应加快

**Comment by TartaricAcid** [comment]
这是由于动画的制作者导致的问题，其默认使用了固定数值来播放动画，而不是使用 molang 函数来设置动画的播放速度。

可以考虑为默认动画添加 molang 来调节播放速度，但是其他人制作的动画问题无法解决
