### ISSUE TITLE
可能需要修复模型解析的问题

### ISSUE THREAD

**Issue by Windywalker** [TartaricAcid/ysm#61]
![2024-02-14_22 40 49](https://github.com/TartaricAcid/ysm/assets/54424584/f2a6ec61-5424-4d13-94b6-2a528cc37966)
模组自带的酒狐模型无法解析？？？

**Comment by TomatoPuddin** [comment]
明天修复

**Comment by TartaricAcid** [comment]
已知问题，下个版本修复

**Comment by TartaricAcid** [comment]
已修复
