### ISSUE TITLE
在1.20.4版本运行 ysm 1.1.5-hotfix-2 时进入选择模型菜单会导致崩溃

### ISSUE THREAD

**Issue by HXYMCH** [TartaricAcid/ysm#67]
在1.20.4版本运行 ysm 1.1.5-hotfix-2 时进入选择模型菜单会导致崩溃

游戏信息：
       Minecraft 1.20.4
       Fabric 0.15.6
       ysm 1.1.5-hotfix-2

[crash-2024-02-18_17.19.35-client.txt](https://github.com/TartaricAcid/ysm/files/14329194/crash-2024-02-18_17.19.35-client.txt)
[crash-2024-02-18_17.26.25-client.txt](https://github.com/TartaricAcid/ysm/files/14329195/crash-2024-02-18_17.26.25-client.txt)
[crash-2024-02-18_17.43.40-client.txt](https://github.com/TartaricAcid/ysm/files/14329196/crash-2024-02-18_17.43.40-client.txt)
以上是三次崩溃的crash report

**Comment by yuyanMC** [comment]
貌似是因为ysm 1.1.5-hotfix-2使用了1.20.1的CheckboxWidget的init方法，而1.20.3开始mojang把这个方法改了，导致当前版本的ysm在1.20.4上不再可用
我尝试在字节码层面上将其改到1.20.4的init方法，然而仍会出现其他错误导致的崩溃

**Comment by TartaricAcid** [comment]
该版本只适用于 1.20.1 和 1.20
