### ISSUE TITLE
F3+T刷新资源包后崩溃问题

### ISSUE THREAD

**Issue by wdnmd23333fdhsuidus** [TartaricAcid/ysm#7]
F3+T刷新资源包后模型不会显示,且刷新资源包后尝试打开ysm菜单会导致MC崩溃

**Comment by wdnmd23333fdhsuidus** [comment]
[crash-2023-05-11_20.37.07-client.txt](https://github.com/TartaricAcid/ysm/files/11452314/crash-2023-05-11_20.37.07-client.txt)
crash-report放这里（

**Comment by TartaricAcid** [comment]
你这个版本的模组不是我发布的
