### ISSUE TITLE
1.2.0版本下alex模型错位

### ISSUE THREAD

**Issue by hu7x** [TartaricAcid/ysm#73]
**测试模组版本：**forge-1.20-1.2.0-hotfix3-minified-production
**模组列表**：Geckolib-forge-1.20.1-4.4  yesstevemodel-forge-1.20-1.2.0-hotfix3-minified-production
问题描述：在主手持剑、三叉戟的情况下会出现模型错位问题
![image](https://github.com/TartaricAcid/ysm/assets/77626528/8a34699d-6fa3-447c-9663-eb85211d484e)
![image](https://github.com/TartaricAcid/ysm/assets/77626528/42101f9f-fae9-43c1-a215-58f4f0b73355)

**Comment by KLuoNuoYa** [comment]
已确认为模型动画套用问题，将在未来版本修复

**Comment by TartaricAcid** [comment]
Fix in 2.2.1
