### ISSUE TITLE
最新版 1.20 不支持 mac os

### ISSUE THREAD

**Issue by SharpOwO** [TartaricAcid/ysm#79]
mac 安装1.20 版本显示不支持 mac os

**Comment by yuyanMC** [comment]
macOS12.6 MacbookPro2017 Minecraft1.20.1 FabricLoader0.15.7 YesSteveModel1.1.5-hotfix2 测试并没有问题 你是不是安装了错误的游戏版本

**Comment by heipiao233** [comment]
Linux也不行

**Comment by TomatoPuddin** [comment]
玩游戏就好好的用 windows

**Comment by yuyanMC** [comment]
> Linux也不行

Linux不行我挺意外的，因为我看到了libysm-core.so，理论上应该是能适配linux的。macOS不适配是因为我确实没有看到任何的dylib文件，当然也可能是其他原因。

**Comment by yuyanMC** [comment]
> 玩游戏就好好的用 windows

请不要以保护源代码为由放弃对macOS的支持。我并非反对利用加壳技术来保护源代码的行为，但如果为了保护源代码而放弃对macOS的支持，我们是无法容忍的。

**Comment by heipiao233** [comment]
> 玩游戏就好好的用 windows

@TomatoPuddin 一个小小的YSM模组让我第一次知道非Windows用户不是人

**Comment by KLuoNuoYa** [comment]
> 请不要以保护源代码为由放弃对macOS的支持。我并非反对利用加壳技术来保护源代码的行为，但如果为了保护源代码而放弃对macOS的支持，我们是无法容忍的。

(找人问了下其他群的大佬)
![image](https://github.com/TartaricAcid/ysm/assets/153290281/65accc46-0640-4d74-9bde-ed94ecbc11e2)

**Comment by yuyanMC** [comment]
> > 请不要以保护源代码为由放弃对macOS的支持。我并非反对利用加壳技术来保护源代码的行为，但如果为了保护源代码而放弃对macOS的支持，我们是无法容忍的。
> 
> (找人问了下其他群的大佬) ![image](https://private-user-images.githubusercontent.com/153290281/316072839-65accc46-0640-4d74-9bde-ed94ecbc11e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyNjc4NDEsIm5iZiI6MTcxMTI2NzU0MSwicGF0aCI6Ii8xNTMyOTAyODEvMzE2MDcyODM5LTY1YWNjYzQ2LTA2NDAtNGQ3NC05YmRlLWVkOTRlY2JjMTFlMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNFQwODA1NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MWZiZTdkNjFkYjIxZDczYjA5ZGU5MWY3NWE3ZmVjZWVjMGY1ODU5MGIwMTc0YzE3OTc3ZmRmNzQyODUyNTdlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.oYPCMXc_IIIGLIbPJiOPxFhSgd1qvXfzBlsZpKpjyow)

所以说啊，此时成本最低的方式就是不加壳。如果加壳就做不到发布macOS版本，那就不要加。macOS的用户占到了所有电脑用户的15%，并不是一个小数字，请不要忽视macOS玩家的存在。

**Comment by KLuoNuoYa** [comment]
> 所以说啊，此时成本最低的方式就是不加壳。如果加壳就做不到发布macOS版本，那就不要加。macOS的用户占到了所有电脑用户的15%，并不是一个小数字，请不要忽视macOS玩家的存在。

如果不加壳，请问您如何防止加密模型被破解？

**Comment by KLuoNuoYa** [comment]
另一方面，我并不见得无法移植MacOS版本和加壳有关系

**Comment by heipiao233** [comment]
你们是不知道DRM吗？

**Comment by KLuoNuoYa** [comment]
> 你们是不知道DRM吗？

DRM一般是防止模型被二次转卖，不是防止模型被拆包

**Comment by yuyanMC** [comment]
> 另一方面，我并不见得无法移植MacOS版本和加壳有关系

我同意你的说法，确实有很多加壳工具支持macOS，但是如果不是因为加壳，为什么这个版本开始macOS的支持被抛弃了呢？

**Comment by KLuoNuoYa** [comment]
> 我同意你的说法，确实有很多加壳工具支持macOS，但是如果不是因为加壳，为什么这个版本开始macOS的支持被抛弃了呢？

LWJGL（大概

**Comment by yuyanMC** [comment]
> > 我同意你的说法，确实有很多加壳工具支持macOS，但是如果不是因为加壳，为什么这个版本开始macOS的支持被抛弃了呢？
> 
> LWJGL（大概

LWJGL有对macOS的官方支持，如果真是LWJGL那就离谱了

**Comment by TartaricAcid** [comment]
![image](https://github.com/TartaricAcid/ysm/assets/19620085/032d87b1-99a7-4919-ba43-de4a0b68d3c9)
只有 1.47% 啊，哪来的 15% 啊

**Comment by yuyanMC** [comment]
> ![image](https://private-user-images.githubusercontent.com/19620085/340594493-032d87b1-99a7-4919-ba43-de4a0b68d3c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3MjEyNDEsIm5iZiI6MTcxOTcyMDk0MSwicGF0aCI6Ii8xOTYyMDA4NS8zNDA1OTQ0OTMtMDMyZDg3YjEtOTlhNy00OTE5LWJhNDMtZGU0YTBiNjhkM2M5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjMwVDA0MTU0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwM2QyOTM1MTVkZjExODA3YjIyMWZmODkzYzU3NGJiYTJhNTIzNDFiMDYwNWRmZWRkMTk2ZWJhOWRlMjc0ZGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PklJ1KFlkFoStcypp9IR6CmTjlxqFQlURRnY3B5-PiY) 只有 1.47% 啊，哪来的 15% 啊

据我了解，这份数据来自Steam。Steam的数据是存在严重的幸存者偏差的，很多mac用户实际上并不使用Steam。我的数据来源是在某Minecraft服务器中发起的，我个人认为数据会更加准确。

**Comment by KLuoNuoYa** [comment]
> > ![image](https://private-user-images.githubusercontent.com/19620085/340594493-032d87b1-99a7-4919-ba43-de4a0b68d3c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3MjEyNDEsIm5iZiI6MTcxOTcyMDk0MSwicGF0aCI6Ii8xOTYyMDA4NS8zNDA1OTQ0OTMtMDMyZDg3YjEtOTlhNy00OTE5LWJhNDMtZGU0YTBiNjhkM2M5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjMwVDA0MTU0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwM2QyOTM1MTVkZjExODA3YjIyMWZmODkzYzU3NGJiYTJhNTIzNDFiMDYwNWRmZWRkMTk2ZWJhOWRlMjc0ZGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PklJ1KFlkFoStcypp9IR6CmTjlxqFQlURRnY3B5-PiY) 只有 1.47% 啊，哪来的 15% 啊
> 
> 据我了解，这份数据来自Steam。Steam的数据是存在严重的幸存者偏差的，很多mac用户实际上并不使用Steam。我的数据来源是在某Minecraft服务器中发起的，我个人认为数据会更加准确。

那为什么Mac用户不用Steam呢？
不就是因为Steam的游戏玩不了吗
为什么玩不了？
不兼容
为什么不兼容？
没有移植
为什么没有移植？
你给Mac写代码首先你得有个Mac

**Comment by KLuoNuoYa** [comment]
> 那为什么Mac用户不用Steam呢？ 不就是因为Steam的游戏玩不了吗 为什么玩不了？ 不兼容 为什么不兼容？ 没有移植 为什么没有移植？ 你给Mac写代码首先你得有个Mac

YSM的特殊性使其根本无法使用交叉编译等方法来使其直接编译MacOS版本，只能手动适配

**Comment by KLuoNuoYa** [comment]
> 据我了解，这份数据来自Steam。Steam的数据是存在严重的幸存者偏差的，很多mac用户实际上并不使用Steam。我的数据来源是在某Minecraft服务器中发起的，我个人认为数据会更加准确。

另外，你的数据来自“某Minecraft服务器”，那么请问这个服务器有多少用户？使用Mac的又有多少？

**Comment by KLuoNuoYa** [comment]
附：死亡搁浅Mac版我也看了，那个是靠转译跑起来的，是基于Wine改出来的Game Porting Toolkit

**Comment by TTsdzb** [comment]
客户端限定平台为 Windows x86_64 勉强可以理解，毕竟用户占大头。为何服务端就直接不管了（#140）？Windows Server 很好用吗

**Comment by KLuoNuoYa** [comment]
> 客户端限定平台为 Windows x86_64 勉强可以理解，毕竟用户占大头。为何服务端就直接不管了（#140）？Windows Server 很好用吗

1. 谁没事用MacOS开服
2. 有Linux x86_64 服务端支持

**Comment by MiskaDaeve** [comment]
> > 客户端限定平台为 Windows x86_64 勉强可以理解，毕竟用户占大头。为何服务端就直接不管了（#140）？Windows Server 很好用吗
> 
>     1. 谁没事用MacOS开服
> 
>     2. 有Linux x86_64 服务端支持

This is a kind of discrimination to some players
