### ISSUE TITLE
坐在玩家肩膀上的鹦鹉不被渲染

### ISSUE THREAD

**Issue by PopSlime** [TartaricAcid/ysm#86]
## 描述
[鹦鹉](https://zh.minecraft.wiki/w/%E9%B9%A6%E9%B9%89)被驯服后会有[坐在玩家肩膀上](https://zh.minecraft.wiki/w/%E9%B9%A6%E9%B9%89#%E5%9D%90%E5%9C%A8%E8%82%A9%E8%86%80%E4%B8%8A)的行为，但是坐在玩家肩膀上的鹦鹉在 YSM 模型中不被渲染。

## 注释
玩家的两个肩膀上可以各坐一只鹦鹉。

## 参考
- 相关 NBT：[玩家存储格式](https://zh.minecraft.wiki/w/%E7%8E%A9%E5%AE%B6%E5%AD%98%E5%82%A8%E6%A0%BC%E5%BC%8F)中的 `ShoulderEntityLeft` 和 `ShoulderEntityRight`

**Comment by TartaricAcid** [comment]
已在新版本修正

**Comment by PopSlime** [comment]
确认修复，感谢
