### ISSUE TITLE
Waving animation Fabric/Forge 1.20.1

### ISSUE THREAD

**Issue by Himenou** [TartaricAcid/ysm#88]
The waving animations, such as "swing_hand" and "swing#minecraft:swords" only last for 0.25 seconds in game, even though the animation in Blockbench is longer. The wiki states that the animation will not be interrupted until it is completed, so I don't understand why it stops.

**Comment by KLuoNuoYa** [comment]
What is your YSM mod version?

**Comment by Himenou** [comment]
1.20 fabric 1.1.5 hotfix 2, I also tried on forge with 1.20 1.1.5 hotfix 2

**Comment by KLuoNuoYa** [comment]
> 1.20 fabric 1.1.5 hotfix 2, I also tried on forge with 1.20 1.1.5 hotfix 2

Please upgrade to [1.2.0 hotfix 4](https://modrinth.com/mod/yes-steve-model/version/kOF1q7HV)

**Comment by Himenou** [comment]
Thanks! Will there be an update for it to work with fabric as well?

**Comment by KLuoNuoYa** [comment]
> Thanks! Will there be an update for it to work with fabric as well?

I think it will, it's only a matter of time
