### ISSUE TITLE
[规范请求] 请求记录模型元数据

### ISSUE THREAD

**Issue by norycio** [TartaricAcid/ysm#90]
本次为规范请求，希望扩展对模型更多的元数据记录，可包括如下内容：
1. 模型名称（必选）
2. 模型发布日期
3. 模型版本（必选）
4. 推荐的YSM版本（必选）
5. 模型作者（必选）
6. 作者个人主页
7. 本模型的订阅、下载、更新地址（可在哪里获取本模型）
8. 是否二创
8.1 二创原作来源
9. 是否NSFW
10. 作者的其他说明内容
这些内容可在游戏中的模型界面查看、可在BlockBench中查看；
而在模型制作完成并导出.ysm后不可被编辑。

这项功能可以维护模型作者以及玩家们的合法权益，同时便于模型的使用和管理。

此外希望能解除模型文件命名限制。

**Comment by KLuoNuoYa** [comment]
> 此外希望能解除模型文件命名限制。

这个没办法，MC本身的限制

**Comment by KLuoNuoYa** [comment]
> 1. 模型名称（必选）
> 2. 模型发布日期
> 3. 模型版本（必选）
> 4. 推荐的YSM版本（必选）
> 5. 模型作者（必选）
> 6. 作者个人主页
> 7. 本模型的订阅、下载、更新地址（可在哪里获取本模型）
> 8. 是否二创
>    8.1 二创原作来源
> 9. 是否NSFW
> 10. 作者的其他说明内容
>     这些内容可在游戏中的模型界面查看、可在BlockBench中查看；
>     而在模型制作完成并导出.ysm后不可被编辑。

如果以上仅仅是显示的话，其实当前版本已经实现
![image](https://github.com/TartaricAcid/ysm/assets/153290281/14082637-e7fa-4681-af0c-29013b85e979)

**Comment by KLuoNuoYa** [comment]
可以直接写描述

**Comment by norycio** [comment]
抱歉我并没有制作过ysm，以为这整块文字均为描述内容；所以那个绿色方框后就是记录的数据吗？
那的确基本满足了请求内容，但不够完善。
在实际使用过程中，还是有很多模型并未添加这些记录；我目前知道这些模型使用BlockBench的某个特定插件制作是这样吗？我们能否在源头上规范，也就模型作者在制作时？如果需要请给我地址，我可以去目标下提Issues :)

此外：
本模组仍处于开发更新阶段，相应的有逐步修改和添加的内容及特性，也就是会出现老模型不能完全发挥新版模组、新模型在老版本模组上不宜适用，所以我认为先前提到的3、4两点应当被规范。
还有第9点，MC更多的是一类社区游戏；现阶段很多的模型作者利用模组新版的强大特性，制作模型的衣着、动作时多少都有“夹带私货”，我并非在这里完全否定这一点，但对于用力过猛的作者们，他们的模型的确不适宜出现在大多数服务器当中。因此第9点应当被规范。
如果模型这些数据信息能得到记录，可以很方便玩家和服务器管理人员。

最后，出于已知信息及上述考量，能否在游戏中添加模型筛选？如在模型选取界面（你上图示），添加“是否包含NSFW”和“是否强制匹配当前YSM版本”（或类似）的筛选？
以我浅薄见解，如果这些元数据被独立而并非一股脑记录在描述板块，这个功能也许能相对容易的实现。也是我一开始用词记录模型元数据的理由。
希望能为本模组开发人员提供一点有意义的见地。祝好。

**Comment by KLuoNuoYa** [comment]
> 所以那个绿色方框后就是记录的数据吗？

这些是写在main里面的，可以自行添加
![image](https://github.com/TartaricAcid/ysm/assets/153290281/7fb501ac-f8f7-4636-98ab-b897e5b5f472)

> 在实际使用过程中，还是有很多模型并未添加这些记录

非强制要求，作者可以不写，这个东西本来就是个可选的内容，给玩家一些提示，而且大部分模型并没有特殊的内容（尤其是一部分修改自默认模型的模型），没有必要去特意填写这部分内容

> 本模组仍处于开发更新阶段，相应的有逐步修改和添加的内容及特性，也就是会出现老模型不能完全发挥新版模组、新模型在老版本模组上不宜适用，所以我认为先前提到的3、4两点应当被规范。

这个几乎不可能
首先，YSM本身就进行了一次大重构，从纯Java转为了JNI，添加了大量新特性，并且更新了加密系统，新版模型根本不可能在旧版模组上加载
而且模型特性是需要模型作者来实现的，所有的动画，除非你只需要调用内置的默认模型动画，否则需要模型作者自己实现
**不管如何，我们始终希望玩家能够一直跟进最新版，而不是成为一个版本的钉子户**

> 还有第9点，MC更多的是一类社区游戏；现阶段很多的模型作者利用模组新版的强大特性，制作模型的衣着、动作时多少都有“夹带私货”，我并非在这里完全否定这一点，但对于用力过猛的作者们，他们的模型的确不适宜出现在大多数服务器当中。因此第9点应当被规范。

作者在发布的时候一般会注明会有不适宜内容，这个主要看使用者如何使用（“忽略风险，继续访问”），另外服务端一般是没有GUI的，提示不好做

> 如果模型这些数据信息能得到记录，可以很方便玩家和服务器管理人员。

请问您打算如何在不加载模组的情况下读取信息呢？

**Comment by norycio** [comment]
感谢回复。

> 请问您打算如何在不加载模组的情况下读取信息呢？

先说最后一条，其实并不是在不加载模组的情况下读取 XD
是在加载模组加载模型后这一阶段
~~（如果能在blockbench-ysm查看就更好了~~

> 作者在发布的时候一般会注明会有不适宜内容，这个主要看使用者如何使用（“忽略风险，继续访问”），另外服务端一般是没有GUI的，提示不好做

也许服务端的提示可以不用做，服务器管理员可以按任意形式，比如全局公告全局广播甚至服务器介绍页面完成说明本服无nsfw或者部分模型含有nsfw，总之起到告知作用就行。这部分和这个问题无关，不细说。
但如果玩家进行游戏，他选择模型时，是否应当知晓哪些模型包含nsfw内容？
我的意思是，目前服务器中的模型均有管理员上传，玩家不知道模型来源作者有无注明。
然后如果模组可以读取模型这种标签，那能不能按这种标签，快速筛选显示的内容？

> 这个几乎不可能
首先，YSM本身就进行了一次大重构，从纯Java转为了JNI，添加了大量新特性，并且更新了加密系统，新版模型根本不可能在旧版模组上加载
而且模型特性是需要模型作者来实现的，所有的动画，除非你只需要调用内置的默认模型动画，否则需要模型作者自己实现
不管如何，我们始终希望玩家能够一直跟进最新版，而不是成为一个版本的钉子户

感谢解释，我为我的考虑不周抱歉。

> 这些是写在main里面的，可以自行添加

现在已经知悉main中包含的info，大部分问题都没了:)，但好像没有版本，能否添加version字段？


最后和上面内容无关——在alt+y的模型界面中，模型显示的名称能否展示为info中的name而不是模型文件名？
（看完info刚想到。很多没法直接读到文件信息的场景下，我会把信息记录在文件名中方便整理。所以文件名多数时候又长又乱。

祝好。

**Comment by norycio** [comment]
感谢回复。

> 请问您打算如何在不加载模组的情况下读取信息呢？

先说最后一条，其实并不是在不加载模组的情况下读取 XD
是在加载模组加载模型后这一阶段
~~（如果能在blockbench-ysm查看就更好了~~

> 作者在发布的时候一般会注明会有不适宜内容，这个主要看使用者如何使用（“忽略风险，继续访问”），另外服务端一般是没有GUI的，提示不好做

也许服务端的提示可以不用做，服务器管理员可以按任意形式，比如全局公告全局广播甚至服务器介绍页面完成说明本服无nsfw或者部分模型含有nsfw，总之起到告知作用就行。这部分和这个问题无关，不细说。
但如果玩家进行游戏，他选择模型时，是否应当知晓哪些模型包含nsfw内容？
我的意思是，目前服务器中的模型均有管理员上传，玩家不知道模型来源作者有无注明。
然后如果模组可以读取模型这种标签，那能不能按这种标签，快速筛选显示的内容？

> 这个几乎不可能
首先，YSM本身就进行了一次大重构，从纯Java转为了JNI，添加了大量新特性，并且更新了加密系统，新版模型根本不可能在旧版模组上加载
而且模型特性是需要模型作者来实现的，所有的动画，除非你只需要调用内置的默认模型动画，否则需要模型作者自己实现
不管如何，我们始终希望玩家能够一直跟进最新版，而不是成为一个版本的钉子户

感谢解释，我为我的考虑不周抱歉。

> 这些是写在main里面的，可以自行添加

现在已经知悉main中包含的info，大部分问题都没了:)，但好像没有版本，能否添加version字段？


最后和上面内容无关——在alt+y的模型界面中，模型显示的名称能否展示为info中的name而不是模型文件名？
（看完info刚想到。很多没法直接读到文件信息的场景下，我会把信息记录在文件名中方便整理。所以文件名多数时候又长又乱。

祝好。

**Comment by TartaricAcid** [comment]
新版本已经规范化了，到时候会发布相关说明文档
![image](https://github.com/TartaricAcid/ysm/assets/19620085/be77d4a2-306c-4897-a200-63d544a375dd)

**Comment by TartaricAcid** [comment]
Fix in 2.2.1

**Comment by yuyanMC** [comment]
> > 此外希望能解除模型文件命名限制。
> 
> 这个没办法，MC本身的限制

我觉得并不是MC本身的限制
MC本体中存在这一限制的只有Identifier，我个人推测ysm中代码是将文件名直接转换成Identifier作为模型的id，才会导致这个问题。实际上解决这个问题的方法很多，比较不好但是省事的如转换为哈希值后转换成Identifier，处理比较得当的方法为将文件名尝试转换为Identifier能够接受的参数等

**Comment by TartaricAcid** [comment]
@yuyanMC 已经在 2.2.1 版本修正此问题
