### ISSUE TITLE
[功能请求]允许客户端主动向服务端上传模型，同时在服务端配置文件中（如果有）添加是否允许主动上传选项

### ISSUE THREAD

**Issue by Hoshino-Yumetsuki** [TartaricAcid/ysm#91]
这个功能可以使服务端对于模型的管理更加便捷，省去了服务端手动添加模型再开放权限的步骤。

关于这个功能的一些细节上可以参考[#90](https://github.com/TartaricAcid/ysm/issues/90)的建议，如关于模型是否为NSFW，单独开一条数据以布尔值的方式记录这条模型是否为NSFW，并且可以在服务端控制是否允许显示此类模型

关于这个功能也可以考虑另外一种实现方式，即不在服务端保存模型或临时保存模型，仅作为将客户端模型向其他玩家显示的方式

**Comment by TartaricAcid** [comment]
其实因为原版对数据包大小的限制，还有安全性的考虑，我觉得之前设计的客户端向服务器游戏内上传模型包并不安全
