### ISSUE TITLE
可以把mod修改成 客户端不安装也能进入服务器嘛

### ISSUE THREAD

**Issue by junjunya2020** [TartaricAcid/ysm#95]
您好作者 可以把mod修改成 客户端不安装也能进入服务器嘛，我在mohist端使用了您的mod 客户端必须安装forge 并且使用 ysm才能进入服务器 应该修改fml就可以了 如果可以服务器就可以多种客户端加入了

**Comment by TartaricAcid** [comment]
啊？1.2.0 不是已经可以这样做了么？？？？？
