### ISSUE TITLE
YSM client is not supported on linux

### ISSUE THREAD

**Issue by FDscend** [TartaricAcid/ysm#97]
- **Mod version**: yesstevemodel-forge-1.20-1.2.0-hotfix4.jar
- **MC version**: 1.20.1
- **Forge version**: 47.0.35
- **Java Version**: 17.0.10
- **OS**: Ubuntu 22.04.4 LTS

---

- 仅将模组改为 `yesstevemodel-1.20-release-1.1.5-hotfix-2.jar` ，游戏能够正常加载
- 仅更改 forge /  java 版本，仍然显示 `YSM client is not supported on linux`
- 在 Windows 10 没遇到

# BTW

虽然模组说明里要求了文件名格式， 但 `yesstevemodel-1.20-release-1.1.5-hotfix-2.jar` 在 Ubuntu 中确实可以正确识别 `中文.ysm` ，如图：

![](https://img2.imgtp.com/2024/04/17/vi7wWUA1.png)

而在 Windows 10 中会显示为乱码，如图：

![](https://img2.imgtp.com/2024/04/17/c9BjTXQM.jpg)

> 我不清楚是什么原因导致的差异，但还是期待在 Windows 也能使用中文文件名（虽然 1.2.0 已经不读取中文文件了……
> 
> 如果开发者已经了解该情况，那就请忽略 Orz

**Comment by TartaricAcid** [comment]
Linux 客户端目前不支持

**Comment by junjunorganization** [comment]
https://web.archive.org/web/20240730025323/https://github.com/TartaricAcid/ysm/issues/79
