### ISSUE TITLE
[FEATUER REQUEST] 希望提供 Linux 支持

### ISSUE THREAD

**Issue by Seele-Vollerei32** [TartaricAcid/ysm#99]
RT, Linuxer 也需要游戏, 例如隔壁游戏巨头 Steam 已经开始全线支持 Linux, 本模组也该跟进一下时代吧.
相同 Issue #97

**Comment by yuyanMC** [comment]
其实1.1.5版本是支持linux的，但是1.2.0给win x64以外的系统全砍了

**Comment by Seele-Vollerei32** [comment]
只是简单的没有做二进制支持 (当然不排除用Cpp重构遇到了兼容性问题).

**Comment by Seele-Vollerei32** [comment]
> 只是简单的没有做二进制支持 (当然不排除用Cpp重构遇到了兼容性问题), 同时有做 Linux x64 的服务端支持, see below ![图片](https://private-user-images.githubusercontent.com/83913312/325985101-43ab4801-fdb8-4507-abb8-68c5af603294.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxMzY3NTcsIm5iZiI6MTcxNDEzNjQ1NywicGF0aCI6Ii84MzkxMzMxMi8zMjU5ODUxMDEtNDNhYjQ4MDEtZmRiOC00NTA3LWFiYjgtNjhjNWFmNjAzMjk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI2VDEzMDA1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxM2E3MjAwZTE3ZjI5MWI1ZDE5YzM0M2ZhZjI0M2Y5ZmM4YWQyNGI1MDQyYjUzNTRmZTE4MGFhMWI1M2M4ZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yQc0pfaZU01fBwDUUqejwGsHRfvy-hLtl09uYT3A78Q)

同时这也大概是被杀软杀的原因(放出了一些不明二进制)

**Comment by TartaricAcid** [comment]
Linux 客户端目前不支持

**Comment by junjunorganization** [comment]
https://web.archive.org/web/20240730025323/https://github.com/TartaricAcid/ysm/issues/79
